### ISSUE TITLE
Don't work on background mode. 

### ISSUE THREAD

**Issue by imhj** [Baseflow/flutter-geolocator#1005]
## 💬 Questions and Help

I use geolocator plug-in. 
It's so great. 
Now, I want to save locate it every 10 minites. it worked. but times later. my phone has changed in background mode. 
Then ... 
`Position pos = await Geolocator.getCurrentPosition();` funtion is not processing. 
I using isolate. before `getCurrentPosition();` I checked `DateTime.now();` function to check where is work well or not in background mode. 
But. `DateTime.now();` function work normally. only `getCurrentPosition();` function has not process but passing. 

This function is running on background mode. Please help me.. 

```dart
void onSendData(FlutterBackgroundService service) async {
  print(DateTime.now().toString().substring(0, 19));     => I/flutter (30585): 2022-03-09 23:59:23
  bool isLocationServiceOn = await Geolocator.isLocationServiceEnabled();
  print("loc_serivce - ${isLocationServiceOn}");           => I/flutter (30585): loc_serivce - true
  LocationPermission permission = await Geolocator.checkPermission();
  print("permission - ${permission}");                          => I/flutter (30585): permission - LocationPermission.whileInUse
  if (permission == LocationPermission.denied) {
    permission = await Geolocator.requestPermission();
  }
  Position pos = await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.high,
      forceAndroidLocationManager: true);
}
```

debug message has same output on foreground mode and background mode.

**Comment by mvanbeusekom** [comment]
Hi @imhj,

This is not how background support works. Currently you can only listen to a position stream (using the `getPositionUpdates()` method) and when an app moves into the background the stream will stay alive and position updates will be delivered.

You cannot however create an isolate and make call to the `getCurrentPosition()` method. This will not work since Flutter method channels are not registered when using an isolate and the messages will not arrive at the native side.

**Comment by imhj** [comment]
Then can you tell me how it works?
If that doesn't work, is there a site where I can get help?

**Comment by arjdesign** [comment]
@mvanbeusekom  I do not see `getPositionUpdates()`  function as you mentioned in your comment above.

**Comment by somitBond** [comment]
@mvanbeusekom 
I am looking for continues user location position update while app is in background; but It is not working like so. 
When app is in foreground and switch into background for first time it does return location.
I am using 8.2.0 version.

getPositionUpdates() this method does not exist.

**Comment by mvanbeusekom** [comment]
@arjdesign, @somitBond apologies the correct method is called `getPositionStream`.

Note that while your app is in the background it will not actively receive position updates. It will keep the location service alive and will deliver the positions when the app comes back to the foreground.

**Comment by somitBond** [comment]
@mvanbeusekom
Thank you for the reply. Is there any way to achieve that or Geolocator is going to add that feature in near future. Actually this is very important for my app to track location at given interval.

Thank you.

**Comment by mvanbeusekom** [comment]
There is an idea on how to handle this, however this would require a large rewrite of the plugin. The main problem is that instead of a stream the position updates will have to be delivered through a callback method which can be called from a background isolate.

I am slowly working towards supporting this, however this will not be on the short term.

**Comment by mathklk** [comment]
> Note that while your app is in the background it will not actively receive position updates. It will keep the location service alive and will deliver the positions when the app comes back to the foreground. @mvanbeusekom 

Does that mean it's not possible at all do get position updates while the app is in the background? Is that a limitation of this plugin or of flutter itself?
