### ISSUE TITLE
GetCurrentPosition doesn't return a location when Precise location is turned off in Settings

### ISSUE THREAD

**Issue by rohnsht** [Baseflow/flutter-geolocator#1027]
## 🐛 Bug Report

When users turn off Precise location from devices settings or chooses **Approximate Location** in android then **getCurrentPosition** doesn't return a value.

### Expected behavior
When an approximate location is used inaccurate location should be returned.

### Reproduction steps
In Android:
Choose **Approximate Location** when **Permission** is requested or go to _Settings > App > Location Permission_ and turn off **Precise Location**.

In Ios:
Go to _Settings > App > Location_ and turn off **Precise Location**.

### Configuration

**Version:** 8.2.0

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by Br4inFreze** [comment]
Same issue for me, tested on an emulator and on physical device (Android 12 for both).
Worked regardless of using the ```forceAndroidLocationManager``` field.

**Comment by 7h30n3** [comment]
## 🐛 Bug Report

I have the same issue as @rohnsht . It's not possible to retrieve a location, when `forceAndroidLocationManager: true` on a device with Google Play Services installed.



### Expected behavior

### Reproduction steps

I have written a minimal example `main.dart`. Just run it with different settings and see for yourself.

```dart
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Geolocator Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

/// Determine the current position of the device.
///
/// When the location services are not enabled or permissions
/// are denied the `Future` will return an error.
Future<Position> _determinePosition() async {
  bool serviceEnabled;
  LocationPermission permission;
  Position pos;

  // Test if location services are enabled.
  permission = await Geolocator.checkPermission();
  if (permission == LocationPermission.denied) {
    permission = await Geolocator.requestPermission();
    if (permission == LocationPermission.denied) {
      // Permissions are denied, next time you could try
      // requesting permissions again (this is also where
      // Android's shouldShowRequestPermissionRationale
      // returned true. According to Android guidelines
      // your App should show an explanatory UI now.
      return Future.error('Location permissions are denied');
    }
  }

  if (permission == LocationPermission.deniedForever) {
    // Permissions are denied forever, handle appropriately.
    return Future.error(
        'Location permissions are permanently denied, we cannot request permissions.');
  }

  // When we reach here, permissions are granted and we can
  // continue accessing the position of the device.
  print('Permission granted, asking for current location.');
  pos = await Geolocator.getCurrentPosition(
    forceAndroidLocationManager: true
  );
  print(pos);
  return pos;
}

class _MyHomePageState extends State<MyHomePage> {
  Position? _pos;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You are here:',
            ),
            Text(
              '$_pos',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () async {
          _pos = await _determinePosition();
          setState(() {});
          },
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
In `build.gradle` 
```
android {
    compileSdkVersion 33
    ...
    }
```
    
In `AndroidManifest.xml`
```
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

My findings are as follows:

Device **with** Google Play Services

- When **forceAndroidLocationManager=true** and **LocationService=off** and **HighAccuracy=off** => _Unhandled Exception: The location service on the device is disabled._

- When **forceAndroidLocationManager=true** and **LocationService=off** and **HighAccuracy=on** => _Unhandled Exception: The location service on the device is disabled._

- When **forceAndroidLocationManager=true** and **LocationService=on** and **HighAccuracy=off** => _No Position, No Error Message) [Here lays the PROBLEM!!!]_

- When **forceAndroidLocationManager=true** and **LocationService=on** and **HighAccuracy=on** => _No Position, No Error Message) [Here lays the PROBLEM!!!]_

Device **without** Google Play Services

- When **forceAndroidLocationManager=true** and **LocationService=off** => _Unhandled Exception: The location service on the device is disabled._

- When **forceAndroidLocationManager=true** and **LocationService=on** => _POSITION_


I hope someone can confirm my findings or even can provide a (quick) fix.

### Configuration

**Version:** 8.2.1 / 9.0.1.

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by alok1upadhyay** [comment]
I have exact same issue on Android 12

**Comment by rafalkk** [comment]
same issue
emulator API 31 and physical device

**Comment by smolugu** [comment]
guys .. any update on this?

**Comment by JeroenWeener** [comment]
Hi everyone!

I am wondering if you are still experiencing this bug on the latest version of `geolocator`. We published a fix today specifically for when using the `LocationManager`. To get the latest version, add `flutter-geolocator: 10.0.1` to your pubspec and run `dart pub upgrade`. This will fetch the latest version of the platform specific packages. You should see `geolocator_android` version `4.2.3` in your `pubspec.lock` file.
