### ISSUE TITLE
Data of accuracy table might be missleading

### ISSUE THREAD

**Issue by JulianBissekkou** [Baseflow/flutter-geolocator#1051]
## 💬 Questions and Help

The accuracy table that we can find in the bottom of the readme.md file is a little confusing.
<img width="513" alt="image" src="https://user-images.githubusercontent.com/36447137/166481917-be55d7cc-e427-41a3-bec2-4b6514a249c0.png">

Many people reported that they got better performance on android when using "best" or "bestForNavigation" and on iOS the other way around.
Can you explain how these numbers where calculated?

**Comment by JulianBissekkou** [comment]
@mvanbeusekom
@martijn00 

Since you are the maintainer of the plugin maybe you have some insights.

**Comment by mvanbeusekom** [comment]
Hi @JulianBissekkou,

The numbers are mend as an indication and are not exact calculations. They are taken (almost 4 years ago) from the documentation on the Android and Apple websites. 

For Apple you provide constants to specify the accuracy (for example `kCLLocationAccuracyHundredMeters`, `kCLLocationAccuracyKilometer` and `kCLLocationAccuracyThreeKilometers`) and the values in the table are taken from there (full details can be found in the [Apple documentation](https://developer.apple.com/documentation/corelocation/cllocationaccuracy?language=objc)).

I have put some effort in finding the Android specific documentation but I am unable to find it, so I can't specify the source information here. 

Since the table is confusing and also not covers all the platforms we support I think it would be good to remove it all together. I will leave this issue open to track this update.
