### ISSUE TITLE
Calling Geolocator.getCurrentPosition() twice or more times fails

### ISSUE THREAD

**Issue by scrabbleknight** [Baseflow/flutter-geolocator#1080]
## 🔙 Regression

Previous versions have never let me down on this one. But Geolocator.getCurrentPosition() is not being called more than once in the same initState(). For example:

```

  Future getLocation() async {
    var currentLocation;
    try {
      currentLocation = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.medium,
      );
    } catch (e) {
      currentLocation = null;
    }
    return currentLocation;
  }

  void getLocation1() async {
    var location = await getLocation();
    print(location);
    print("First");
  }

  void getLocation2() async {
    var location = await getLocation();
    print(location);
    print("Second");
  }

  @override
  void initState() {
    super.initState();
    getLocation1();
    getLocation2();
  }

```

The console prints "Second" but not "First". When I remove the getLocation2() call, the console prints "First". They are not able to be called in the same frame, and I don't know why this changed. Can this be fixed? Am I missing something?

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
I am assuming you are experiencing this behavior on iOS or macOS. The reason is that Apple doesn't allow multiple active calls to the location stream. What happens is that the `getLocation2` method closes the active request currently running by the `getLocation1` call.

The easiest way to workaround this, is to return the same `Future` if the first request has not been finished yet:

```dart
  late Future<Position> _positionFuture;

  Future<Position> getLocation() async {
    if (_positionFuture != null && !_positionFuture!.isCompleted) {
      return _positionFuture;
    }

    _positionFuture = Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.medium,
      );
    return _positionFuture;
  }

  void getLocation1() async {
    var location = await getLocation();
    print(location);
    print("First");
  }

  void getLocation2() async {
    var location = await getLocation();
    print(location);
    print("Second");
  }

  @override
  void initState() {
    super.initState();
    getLocation1();
    getLocation2();
  }
```

It looks like this question is the same as the question "[Flutter - Geolocator package is not calling Geolocator.getCurrentPosition() more than once](https://stackoverflow.com/questions/72604133/flutter-geolocator-package-is-not-calling-geolocator-getcurrentposition-more)" on StackOverflow (going by the code sample). I am therefore going to close this issue, however if you have further questions please leave another comment.
