### ISSUE TITLE
Geolocator.checkPermission() not return LocationPermission.deniedForever

### ISSUE THREAD

**Issue by KirillArtemenko** [Baseflow/flutter-geolocator#1087]
## 🐛 Bug Report

After deny location request.

```
final checkPermission =  await Geolocator.checkPermission();
// checkPermission == LocationPermission.denied

final requestPermission = await Geolocator.requestPermission();
// requestPermission == LocationPermission.deniedForever

checkPermission != requestPermission
```

**Expected behavior**
Method checkPermission must return LocationPermission.deniedForever.
The order and numbers of method calls does not affect the result.

**Steps To Reproduce**

1. Request permissions
2. Deny (once or twice on android)
3. Run this methods
4. See different PermissionStatus from methods

**Tested on:**
- iOS, Version 15.5 real device
- Android, Pixel 4a (last Android version)

**Comment by mvanbeusekom** [comment]
Hi @KirillArtemenko,

Thank you for taking the time and submitting this report. Unfortunately the Android API doesn't allow us to differentiate between `denied` and `deniedForever` when checking for permissions. The `ContextCompat.checkSelfPermission()` method only returns the `PERMISSION_GRANTED` or `PERMISSION_DENIED` states (even when the user selected the "Don't ask me again" option). This is documented clearly on the [Android documentation](https://developer.android.com/training/permissions/requesting#already-granted). Therefore we cannot make the distinction and always return `LocationPermission.denied`. 

Due to a small work around we are however able to determine this as a direct result of the `requestPermission` method and will report this accordingly. More information about this behavior can be found on our [Wiki](https://github.com/Baseflow/flutter-geolocator/wiki/Breaking-changes-in-7.0.0).

On iOS however we report the permissions correctly. Denying permissions will directly result in a `LocationPermission.deniedForever` and the `checkPermission` method will report this accordingly. I have verified this today (just to be sure) using the following code:

```dart
  Future<void> handlePermission() async {
    final requestPermission = await Geolocator.requestPermission();
    print('Requested permission: $requestPermission');

    final checkPermission = await Geolocator.checkPermission();
    print('Checked permission: $checkPermission');
  }
```

Which resulted in the following output after denying permissions:

```text
flutter: Requested permission: LocationPermission.deniedForever
flutter: Checked permission: LocationPermission.deniedForever
```

As the geolocator seems to function properly, I will close this issue now. If you have further inquiries please feel free to leave a comment.
