### ISSUE TITLE
Geolocator doesn't work on windows and MacOs

### ISSUE THREAD

**Issue by RawadZogheib** [Baseflow/flutter-geolocator#1100]
## 🐛 Bug Report

**Code:** 
```dart
Future<Position> determinePosition() async {
    bool serviceEnabled;
    LocationPermission permission;

    // Test if location services are enabled.
    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      // Location services are not enabled don't continue
      // accessing the position and request users of the
      // App to enable the location services.
      return Future.error('Location services are disabled.');
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        // Permissions are denied, next time you could try
        // requesting permissions again (this is also where
        // Android's shouldShowRequestPermissionRationale
        // returned true. According to Android guidelines
        // your App should show an explanatory UI now.
        return Future.error('Location permissions are denied');
      }
    }

    if (permission == LocationPermission.deniedForever) {
      // Permissions are denied forever, handle appropriately.
      return Future.error(
          'Location permissions are permanently denied, we cannot request permissions.');
    }

    // When we reach here, permissions are granted and we can
    // continue accessing the position of the device.
    return await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
}
```

It return "Location permissions are denied" on both (I've add the required permission on MacOs as demanded in the Readme)

**Platform:** 
- [ ] :MacOs
- [ ] :Windows

**Comment by ScottWallace** [comment]
Same here, always returns denied even when service is enabled. No permissions requested in UI, just "denied".

**Comment by DmitrySikorsky** [comment]
Same for me. `await Geolocator.requestPermission()` shows dialog, but even if I allow, then I have denied exception.

**Comment by DirtyNative** [comment]
Any news on this? I am also facing this issue

**Comment by zqin97** [comment]
Facing same problem here

**Comment by mengxiangjian13** [comment]
Same problem here

**Comment by sarabura** [comment]
Same problem here, Windows. Doesn't launch permission request dialog, just returns "denied".

**Comment by mvanbeusekom** [comment]
On Windows the permission dialog is only [shown once for an application](https://learn.microsoft.com/en-us/uwp/api/windows.devices.geolocation.geolocator.requestaccessasync?view=winrt-22621#remarks). When the user denies permissions, the dialog is not displayed anymore when requesting permissions. 

On Windows 11 this behaviour is even more irregular, since applications that are not designed for Microsoft Store are considered "Windows Desktop application" which are all bundled together and share the same permission settings.

Unfortunately I was not able to find a way on Windows to reliably determine if permissions have been denied before and return a `PermantlyDenied` status. 

The suggested solution (coming from [Microsoft](https://learn.microsoft.com/en-us/windows/uwp/maps-and-location/get-location#step-2-get-the-users-location-and-register-for-changes-in-location-permissions)) is to always `requestPermission` and act based on the result:

1. If the result is `denied` redirect the user to the Windows settings.
2. If the result is `granted` you are free to use the location services.

If anyone has a better solution feel free to leave a comment. I would love to consider alternatives. However for now I will close this issue as I see no other option to better resolve this.
