### ISSUE TITLE
Property 'sourceInformation' not found on object of type 'CLLocation 

### ISSUE THREAD

**Issue by kururu-abdo** [Baseflow/flutter-geolocator#1107]
i face this error when try to run on IOS:

Semantic Issue (Xcode): Property 'sourceInformation' not found on object of type 'CLLocation *'

**Comment by hanko0206** [comment]
Any updates on this? badly need the solution since my app totally relies on location data, I am using 
`geolocator: ^8.2.0`

**Comment by florissmit1** [comment]
@kururu-abdo @hanko0206 thanks for reporting this issue. I can reproduce it when building a macOS/iOS application. I'm not sure what the problem is, but I solved it by building the application in xCode instead of through the terminal. I hope this will solve the issue for now. We will look into a proper solution for this, since it's incorrect behaviour.

**Comment by akashsiddhpura** [comment]
i face this error when try to run on IOS:

Semantic Issue (Xcode): Property 'sourceInformation' not found on object of type 'CLLocation *'

**Comment by kururu-abdo** [comment]
thanks
i run it in Xcode and the error has gone

**Comment by ShinMyth** [comment]
I experienced this problem and tried multiple possible solutions such as version downgrade from geolocator: ^9.0.1 to ^8.2.0, flutter pub cache repair and even removing other packages that might have a conflict with geolocator package and also the suggested fix on building it on xcode.

**Comment by rafa-sandoval** [comment]
Hi, we was having the same problem, and it is because of xcode and flutter version, basically it is happening in Flutter 3 with some version of xcode previous to 13.2. For fix this, you need to build direct in xcode and then all flutter command should work again
