### ISSUE TITLE
Why android 33 sdk requirement ?

### ISSUE THREAD

**Issue by adishmuhammed** [Baseflow/flutter-geolocator#1123]
An error says :
One or more plugins require a higher Android SDK version.
Fix this issue by adding the following to C:\Users\sss\Documents\projects\real\recycile_bin_app\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}

is location services only available in android 13 ? which is only available for small number of android users

**Comment by mvanbeusekom** [comment]
No the location services are available on all devices between Android API 16 and Android API 33. 

However we compile the library against the Android API 33 SDK so that we can use al of the latest features API 33 provides. Therefore app developers also have to update their application to compile against SDK 33. Again this doesn't mean the app will only run on Android 13 (API 33) devices.

Here are some resources explaining the concept of `compileSdkVersion`:

- https://proandroiddev.com/compilesdkversion-and-targetsdkversion-what-is-the-difference-b4227c663ba8
- https://stackoverflow.com/a/26694276/5167831
- https://www.youtube.com/watch?v=JEAUTGYmz2s
