### ISSUE TITLE
Why is `Position`'s `timestamp` property nullable?

### ISSUE THREAD

**Issue by jjoelson** [Baseflow/flutter-geolocator#1145]
Thanks for creating this great package!

I was wondering why the `Position` `timestamp` property is `DateTime?` instead of `DateTime`. I did a quick scan of the `getPositionStream` implementation for iOS and Android and it looks like [`CLLocation.timestamp`](https://developer.apple.com/documentation/corelocation/cllocation/1423589-timestamp) and [`android.location.Location.getTime()`](https://developer.android.com/reference/android/location/Location) are the sources and should always return a value. 

I didn't dive into the other platform code because I'm only using iOS and Android. Can I can safely assume that `timestamp` will always be non-null on iOS and Android? Or are there scenarios where it will be null?

**Comment by TimHoogstrate** [comment]
Dear @jjoelson,

In the changelog of version 2.0.1 it is stated that:

`Bug fix where a null reference exception occurs because the timestamp of the `Position` could be `null` when fetching a `Placemark` using the `placemarkFromAddress` or `placemarkFromCoordinates` methods.`

So it seems to have a valid reason to be there. 

Kind regards,

**Comment by TimHoogstrate** [comment]
Resolved by [1362](https://github.com/Baseflow/flutter-geolocator/pull/1362)
