### ISSUE TITLE
LocationAccuracy.best is returning an accuracy around 124m

### ISSUE THREAD

**Issue by tiyebm** [Baseflow/flutter-geolocator#1148]
```
Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
```
This is gives me 124m on android, and it is supposed to be 0-100m, so instead of best or high, we want to be able to pass the required accuracy in meters.

**Comment by mvanbeusekom** [comment]
Hi @tiyebm,

That is unfortunately not how the Android location API works. Android allows setting a priority which determines the accuracy of the location information which is documented [here](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest#setPriority(int)).

The `LocationAccuracy.high` and up will map to the `PRIORITY_HIGH_ACCURACY` priority setting on Android native SDK. 

One thing you can check if the device is using Android 12 or higher has the precise permissions (for example using the [getLocationAccuracy()](https://pub.dev/documentation/geolocator/latest/geolocator/Geolocator/getLocationAccuracy.html) method).

Otherwise the accuracy range mentioned (in this case 0-100m) is just an indication and no guarantee.

I will be closing this issue as this seems out of our hands. Feel free to leave followup questions or comments.

**Comment by tiyebm** [comment]
Thank you for the clarifications, I will take this chance to ask you about `desiredAccuracy: LocationAccuracy.values`, what is it for and how to implement it?

**Comment by mvanbeusekom** [comment]
The `desiredAccuracy` property controls the level of precision the app uses to access location settings. When requesting a location you need to tradeoff between power consumption and accuracy. If you need high accuracy results you should set the `desiredAccuracy` field to `LocationAccuracy.high` or `LocationAccuracy.best` (both result in the highest `Priority.PRIORITY_HIGH_ACCURACY` priority on Android, but have a different effect on iOS and macOS). This however means you will have a heavier load on the battery consumption. 

So if the app can do with less precise results you should lower the accuracy which will result in a lower battery consumption.

**Comment by tiyebm** [comment]
One other question is, is there a way to know the accuracy in meters based on the result of `getCurrentPosition`?

**Comment by mvanbeusekom** [comment]
No there is not an exact measurement, you can however check the `Position.accuracy` field to get an estimation in meters. Documentation here: https://pub.dev/documentation/geolocator_platform_interface/latest/geolocator_platform_interface/Position/accuracy.html

Again this is no guarantee, in general it means the lower the number the more accurate the position.

**Comment by tiyebm** [comment]
Thank you very much for quick response, time and effort.
