### ISSUE TITLE
[Bug] Could not load compiled classes for build file 'D:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-4.1.4\android\build.gradle' from cache.

### ISSUE THREAD

**Issue by alihassan04ali** [Baseflow/flutter-geolocator#1163]
After including this package in flutter sdk 3.3.0 i got error during build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':geolocator_android'.
> Could not load compiled classes for build file 'D:\flutter\.pub-cache\hosted\pub.dartlang.org\geolocator_android-4.1.4\android\build.gradle' from cache.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':geolocator_android' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':geolocator_android' of type org.gradle.api.Project.

**Comment by JeroenWeener** [comment]
Hi @alihassan04ali, thank you for taking the time to file this issue!

This seems to be a gradle cache issue, though it is hard to tell without extra information. You can clear your gradle cache to see if the issue is resolved. If the issue persists, please provide me with the version of the plugin you are using, and ideally a minimum code sample, reproduction steps and the output of `flutter doctor`.
