### ISSUE TITLE
Refactor Position fromMap method to explicitly require Map<String, dynamic>

### ISSUE THREAD

**Issue by kyeshmz** [Baseflow/flutter-geolocator#1165]
## 🏗 Enhancement Proposal
Currently, the interface asks for a `dynamic` type, which is then converted to a `Map<dynamic, dynamic>` though there are operations inside that are looking for a Json - esque type.
The `Map<dynamic, dynamic>`  should be `Map<String, dynamic>` as well as show the user that this type of input is necessary.

### Pitch
It makes it more easier for developers to catch bugs

### Platforms affected (mark all that apply)
- [x ] :iphone: iOS
- [ x] :robot: Android

**Comment by kyeshmz** [comment]
I looked into what might be the problem, but it seems like it is not as easy as just changing the positionMap referenced inside of the models/position.dart to be `Map<String,dynamic>` as many of the internal code is converting from `_InternalLinkedHashMap<Object?, Object?>'` 

There are some instances in which the code just automatically assumes its type, 

geolocator_apple.dart 
```
    _positionStream = positionStream
        .map<Position>((dynamic element) =>
            Position.fromMap(element.cast<String, dynamic>()))
```

The code below is a possible solution, but seems hacky because of the encoding and decoding step
```
 static Position fromMap(dynamic message) {
    final Map<String, dynamic> positionMap = jsonDecode(jsonEncode(message));
```

**Comment by mvanbeusekom** [comment]
Since we depend on the underlying architecture of the [Platform channels](https://docs.flutter.dev/platform-integration/platform-channels) there is no easy way to improve the typing. 

Since this is all internal code and not exposed to the outside I am inclined not to try and improve this any further. Additionally we are planning to migrate to make use of the [Pigeon](https://pub.dev/packages/pigeon) plugin in the near future which would generate all the code needed to communicate with the native platform based on pre-defined contracts. This should further solve this problem. 

I will go ahead and close this issue for now.
