### ISSUE TITLE
iOS: Geolocator.getCurrentPosition() never completes

### ISSUE THREAD

**Issue by gisborne** [Baseflow/flutter-geolocator#1191]
## 🐛 Bug Report

Using current iOS simulator 14.2, emulating a iPhone Pro Max 14. I've set the Info.plist content, and I've been asked and given permission for the app to access location while running.

`Geolocator.getCurrentPosition()` neither completes nor errors.

### Expected behavior

Position returned.

### Reproduction steps

Immediately on starting to draw my home widget, I do this:

```
  bool serviceEnabled;
  LocationPermission permission;

  // Test if location services are enabled.
  serviceEnabled = await Geolocator.isLocationServiceEnabled();
  if (!serviceEnabled) {
    // Location services are not enabled don't continue
    // accessing the position and request users of the
    // App to enable the location services.
    return Future.error('Location services are disabled.');
  }

  permission = await Geolocator.checkPermission();
  if (permission == LocationPermission.denied) {
    permission = await Geolocator.requestPermission();
    if (permission == LocationPermission.denied) {
      // Permissions are denied, next time you could try
      // requesting permissions again (this is also where
      // Android's shouldShowRequestPermissionRationale
      // returned true. According to Android guidelines
      // your App should show an explanatory UI now.
      return Future.error('Location permissions are denied');
    }
  }

  if (permission == LocationPermission.deniedForever) {
    // Permissions are denied forever, handle appropriately.
    return Future.error(
        'Location permissions are permanently denied, we cannot request permissions.');
  }

  // When we reach here, permissions are granted and we can
  // continue accessing the position of the device.
  try {
    var loc = await Geolocator.getCurrentPosition();
    print(loc);
  } catch (e) {
    print(e);
  }
```

I put a breakpoint at `var loc = …` and at `print(e)`. I get to the first, but when I continue at that point, it never gets to the second. ie afaict, Geolocator.getCurrentPosition() never either completes or throws an error.

### Configuration

**Version:** 9.0.2

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by rs-linhlc** [comment]
I have a similar problem but not sure it's the same problem as yours. You can check it out. Here's a few reason I encountered make **getCurrentPosition()** never completes:
- User's location doesn't change from the last time you call **getCurrentPosition()**
- User is in the place that plugin couldn't get location.

It's never complete because default time limit of Geolocator is null, so it will keep stay there forever unless you put time limit in. If you do, it will throw a TimeOutException so you can handle from there. To modify your code:

Position? currentPosition;

```
  try {
    // I set time limit = 15 seconds, but you can change it as you like
    currentPosition = await Geolocator.getCurrentPosition(timeLimit: const Duration(seconds: 15));
    print(currentPosition);
  } catch (e) {
   // Here you can show error message to user 
  // However, if you really need to get user location, use getLastKnownPosition instead.
  currentPosition = await Geolocator.getLastKnownPosition();
  }
```

**Comment by tuandigitalunicorn** [comment]
I think you are running a **fake gps location**.

**Comment by mvanbeusekom** [comment]
Hi @gisborne,

Please make sure that the simulator is actively broadcasting location updates. To do so open the Simulator application and navigate to `Features` -> `Location` in the top menu bar. 

Make sure to set it to any option other then `None`. Note that as @rs-linhlc mentioned it is also possible that the simulator isn't broadcasting location updates because the position hasn't changed since last time. This could happen when the option "Apple" or "Custom Location" is selected. 

Select "City run", "City bicycle ride" or "Freeway drive" options to simulate a constant stream of location changes (at different speeds) or select the "Custom Location" and update the coordinates.

Let me know if this helps. The code example provided works great for me, so closing this issue for now, but would be happy to re-open if the problem persists. In this case please also include the `Info.plist` configuration here.

**Comment by bensonarafat** [comment]
> Hi @gisborne,
> 
> Please make sure that the simulator is actively broadcasting location updates. To do so open the Simulator application and navigate to `Features` -> `Location` in the top menu bar.
> 
> Make sure to set it to any option other then `None`. Note that as @rs-linhlc mentioned it is also possible that the simulator isn't broadcasting location updates because the position hasn't changed since last time. This could happen when the option "Apple" or "Custom Location" is selected.
> 
> Select "City run", "City bicycle ride" or "Freeway drive" options to simulate a constant stream of location changes (at different speeds) or select the "Custom Location" and update the coordinates.
> 
> Let me know if this helps. The code example provided works great for me, so closing this issue for now, but would be happy to re-open if the problem persists. In this case please also include the `Info.plist` configuration here.

This is my answer, i just changed it to running

**Comment by ariefsn** [comment]
hi,
facing same issue, but it's only happened on testflight.
debug with simulator ✅
debug with real device ✅
testflight (not working)

any idea?
