### ISSUE TITLE
Excessive positioning deviation

### ISSUE THREAD

**Issue by China-Xuruize** [Baseflow/flutter-geolocator#1229]
The positioning deviation is 2 kilometers. Is this the problem with my equipment or the plug-in

**Comment by JeroenWeener** [comment]
Hi @China-Xuruize, thank you for filing this issue!

2 km indeed seems like an excessive range deviation. I would not expect such deviation from the plugin. To determine whether this problem originated from the plugin, however, we'd need some extra information.

Could you mention which platform(s) (Android, iOS, etc), which phone brand and -model you are using? Also, could you provide a minimal code sample that showcases your issue? For a minimal code sample you can create a new flutter project, edit `main.dart` and share its contents.

Once this information is available, people might be able to look into this issue and identify its root cause.
