### ISSUE TITLE
[Question]: decimal places after decimal points

### ISSUE THREAD

**Issue by omarbenzekri** [Baseflow/flutter-geolocator#1282]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

Hi
  My question is about the difference between decimal places when using ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION
what I know is that ACCESS_FINE_LOCATION is more precise than ACCESS_COARSE_LOCATION.
Well, when I tried it, ACCESS_FINE_LOCATION returns 6 digits in latitude and longitude but ACCESS_COARSE_LOCATION returns 16 digits.
I expected the opposite since ACCESS_FINE_LOCATION is supposed to be more precise.
am I wrong? Correct me, please.

here's an example of what I get:
                                                 latitude   / longitude  / accuracy
ACCESS_COARSE_LOCATION   XX.468468468468465 / X.6946368516051495 / 2000.0
ACCESS_FINE_LOCATION         XX.4697797        /   X.6927091    / 21.600000381469727

### Version

9.0.2

**Comment by JeroenWeener** [comment]
Hi @omarbenzekri!

The accuracy of the returned location is influenced by multiple factors. As far as I know, there is no accuracy guarantee. The difference between COARSE and FINE is the sources they use to determine the location. For more information, you can have a look at https://developers.google.com/maps/documentation/android-sdk/location#location_permissions.

As for the difference in significant digits you mention, I am not sure why this is happening. However, I do not think it matters much, since the number of significant digits you are receiving are more than what I would assume is the measurement error. This means that for any practical use case, you already get enough precision.

**Comment by omarbenzekri** [comment]
Hi @JeroenWeener 
 Thanks for taking the time to respond and ensuring me. 
  Yes, I do understand that FINE is better than COARSE, however, the difference in digits makes me wonder why? 
Thank you again, I'll go with FINE for a precise location as mentioned.

**Comment by JeroenWeener** [comment]
I am just guessing here, but maybe one of the sources used in the calculation of FINE has less significancy, resulting in an overall decrease in significancy, but an increase of accuracy.

I am going to close this issue for now. If you encounter any other issues or questions with the geolocator plugin, feel free to open a new issue.
