### ISSUE TITLE
[Bug]:  Failed to calculate the value of task ':geolocator_android:processReleaseManifest' property 'packageOverride'.

### ISSUE THREAD

**Issue by kabiln** [Baseflow/flutter-geolocator#1295]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Using geolocator package to build an app with fluttermap.
Everythink works as web-emulator. But once I run the android build, I get the build error message.

### Expected results

-

### Actual results

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':geolocator_android:processReleaseManifest'.

> Failed to calculate the value of task ':geolocator_android:processReleaseManifest' property 'packageOverride'.

> Failed to query the value of property 'applicationId'.

> Package Name not found in /var/workspace/.pub-cache/hosted/pub.dev/geolocator_android-4.2.1/android/src/main/AndroidManifest.xml

### Code sample

<details><summary>Code sample</summary>

```dart
[Paste your code here]
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':geolocator_android:processReleaseManifest'.

> Failed to calculate the value of task ':geolocator_android:processReleaseManifest' property 'packageOverride'.

> Failed to query the value of property 'applicationId'.

> Package Name not found in /var/workspace/.pub-cache/hosted/pub.dev/geolocator_android-4.2.1/android/src/main/AndroidManifest.xml

</details>

**Comment by mvanbeusekom** [comment]
Hi @kabiln,

This issue is most likely caused by an outdated version of Android Gradle Plugin still being used in the Flutter app. Monday we released a new version of the geolocator_android package (version 4.2.1) which internally updated to Android Gradle 7.6.2. 

Since version 7.0 of Android Gradle the use of `applicationId` in the AndroidManifest file is considered deprecated and therefore we also removed it from our AndroidManifest file. However we didn't realise this would cause problems with Flutter applications that still rely on older versions of Android Gradle (pre-7.0). We have just released version 4.2.2 of the geolocator_android package where we put back the `applicationId` in the AndroidManifest file for backward-compatibility reasons. This should fix the problem you are facing, if you have a dependency on the `geolocator` package, please run the `flutter pub upgrade` command to update to the latest version.

We will soon release a major version of the geolocator_android plugin and the necessary documentation on how to update your application to the latest version of Android Gradle. This will however offer developers the option to manually upgrade and go through the migration proces. 

Apologies for the inconvenience caused.
