### ISSUE TITLE
[Question]: Disposing Geolocator services on geolocator foreground 

### ISSUE THREAD

**Issue by omerfarukcelenk** [Baseflow/flutter-geolocator#1319]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Your question

i have issue with geolocator foreground working. when i terminate app geolocator disposing.
![image](https://github.com/Baseflow/flutter-geolocator/assets/71720425/67691e9b-8561-4ab9-bbdc-920cf6ffd992)
i'm using `geolocator: ^9.0.1` version. 
![image](https://github.com/Baseflow/flutter-geolocator/assets/71720425/032707ab-96d5-4ea3-b815-f4418003fb02)
I activated foreground notification config and gived to permission on androidManifest.xml
And ı ask for location permisson but stil geolocator dispossing.
![image](https://github.com/Baseflow/flutter-geolocator/assets/71720425/f4d37691-2424-40fa-96ad-abecdca2ea97)

### Version

9.0.1

**Comment by JeroenWeener** [comment]
Hi @omerfarukcelenk, thank you for your bug report!

It is not clear to me what problem you are describing. Are you saying that the geolocator is terminated when you terminate the application? As that would be expected behavior.

The terminology can be quite confusing. In this case, running in the *foreground* means that the service will run when the app is not in view of the user. However, when the app is killed, the process is also terminated.

We do not yet support *background* location updates. There has been requests from the community to support background location updates. You can track the issue here: #53. You might be able to find some hints there on how to achieve that functionality.
