### ISSUE TITLE
[Question]: is there a way to read each  GPS satellite signal individually? or any code examples? Thanks.

### ISSUE THREAD

**Issue by mw66** [Baseflow/flutter-geolocator#1460]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md).

### Please select for which platform(s) you need help

- [X] Android
- [X] iOS
- [X] Linux
- [X] macOS
- [X] Web
- [X] Windows

### Your question

I want get the raw data (Latitude, Longitude, time, satellite signal strength, satellite id? ...) for each satellite.

Is there a way to read each  GPS satellite signal individually? or any code examples? 

Or any low level library I can use? better to be cross-platform.

Thanks.

### Version

11.0

**Comment by mvanbeusekom** [comment]
Hi @mw66,

Unfortunately there is not. On Android there is a possibility to receive raw NMEA events, however these are not provided on any of the other platforms which is why we currently don't support it in the geolocator. 

We are planning (long term) to refactor the geolocator so that we provide access to the native SDKs which will enable developers to access the NMEA events specifically on Android, however this will still leave the other platforms unsupported.
