### ISSUE TITLE
[Enhancement proposal]: move non-flutter models to new package

### ISSUE THREAD

**Issue by ostk0069** [Baseflow/flutter-geolocator#1512]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [X] iOS
- [X] Linux
- [X] macOS
- [X] Web
- [X] Windows

### Proposal

currently, domain definition models ( such as https://github.com/Baseflow/flutter-geolocator/tree/main/geolocator_platform_interface/lib/src/models ) are non-flutter files. 
Therefore, these files are in file geolocator_platform_interface packeage which depends on flutter.
Separating non-flutter domain codes and others looks much nice, I think.

### Pitch

This will be very helpful for multiple package apps.

**Comment by mvanbeusekom** [comment]
Hi @ostk0069,

These models are specifically meant for the use in the geolocator plugin. We don't intent to otherwise expose these models as that means we will also limit ourselves when updating the models for geolocation purposes. 

You are free to copy the classes and use them in you application according to the license specified in the [LICENSE](https://github.com/Baseflow/flutter-geolocator/blob/main/LICENSE) file of the package.
