### ISSUE TITLE
There should be some way to check if device has GPS receiver. 

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-geolocator#159]
## 🏗 Enhancement Proposal
Referring [this](https://github.com/BaseflowIT/flutter-geolocator/issues/143#issuecomment-450549600)
There should be some way to check whether the device has GPS receiver, so that we can inform users about the limited functionality the app would offer in receiver absence.

## Pitch
I thought `Geolocator.checkGeolocationPermissionStatus` can do the job by returning the status to be either `PermissionStatus.unknown` or `PermissionStatus.restricted`. 

## Platforms affected 
- Android
- iOS

**Comment by mulderpf** [comment]
Agreed, for devices with no GPS receiver, there is unfortunately no exception or anything to crash - it just appears to be looking for the location all the time which is currently upsetting some users.

**Comment by florissmit1** [comment]
We considered implementing your feature request. Android **does** support checking whether a device has one or more methods to report the position of the device using the `LocationManager`. iOS's opposite `CLLocationManager` on the other hand **does not** support this, thus we chose not to implement your feature request. 

We chose not to implement your request because there isn't a reliable way to check whether or not the device has a way to track it's positioning, also taking in account that Android and iOS do support external positioning devices.

For now I will close the issue.
