### ISSUE TITLE
Brazilian cities are a different variable on iOS and Android

### ISSUE THREAD

**Issue by arlucio** [Baseflow/flutter-geolocator#240]
So, that's a very strange bug.

Until where I investigate, `Placemark.locality` is the city name always for iOS and Android, except on **Android** when you use the coordinates/search for a brazilian city, then the city name is `Placemark.subAdministrativeArea `.

Maybe more countries are affected. The strange is that it was working normally with locality until other day.

I'm using this now for brazilian cities:

```
if (Platform.isIOS) city = results.first.locality;
if (Platform.isAndroid) city = results.first.subAdministrativeArea;
```

**Comment by red42** [comment]
Alos, Placemark.administrativeArea returns the full state name on Android and just the two-letter code on iOS.

Android: São Paulo
iOS: SP

**Comment by vinnytwice** [comment]
@arlucio @red42 I see a lot of mess using the geocoding from this plugin.. in my case I use `subAdministrativeArea` as the main city  for my db because otherwise  the queries would be too narrow excluding a good chunk of data.. The problem I'm facing is that on iOS I get a full address while Android is missing street name and the `subAdministrativeArea` parameter returns two different naming messing up the whole logic.. also the returned locale is not correct, results are always in the country locale, not in the asked locale e.g. `Città Metropolitana di Bologna` should be `Metropolitan City of Bologna`

an example of geocoding results for coordinates latitude:44.5013, longitude:11.336,   locale en-US is:

```
iOS:

User db is : comune: Bologna ,address: Via Azzo Gardino 38 ,city: Bologna , zipcode: 40122 , Italy ,region: Emilia–Romagna , ?? Lame

Android:

User db is : comune: Bologna ,address: 28 ,city: Città Metropolitana di Bologna , zipcode: 40122 , Italy ,region: Emilia-Romagna , ?? n/a

```

So until this is solved I'm keeping using GeoDb API  which, while unfortunately doesn't return an address and needs coordinates formatted in ISO6709, has  consistent naming for locale as well.
`Città Metropolitana di Bologna` is  `Metropolitan City of Bologna`
Above coordinates ISO6709 formatted is for the GET request is  `%2B44.5013%2B11.336` . Documentation is quite complete and API is easy to implement but if you need any help setting it up or need a sample code let me know.
Hope this helps you guys.

Cheers

**Comment by mvanbeusekom** [comment]
Since version 6.0.0 the geocoding features are no longer part of the geolocator plugin and moved to their own plugin which can be found [here](https://github.com/baseflow/flutter-geocoding).
