### ISSUE TITLE
getPositionStream() isn't receiving callback properly

### ISSUE THREAD

**Issue by dark-chocolate** [Baseflow/flutter-geolocator#257]
## 🐛 Bug Report
Code used
```
var locationOptions = LocationOptions(accuracy: LocationAccuracy.bestForNavigation);
_geoLocator.getPositionStream(locationOptions).listen((position) {
  print("Speed = ${position.speed}");
});
```

If you are moving, this work as expected no issue, but if you stop moving, the speed doesn't show 0 value. 

### Expected behavior
The speed should be 0

### Reproduction steps
1. Use the above code. 
2. Start moving for few seconds. 
3. Stop moving after that. 
4. The speed shown isn't 0 (which it should be)

**Version:** 
3.0.1

**Platform:** 
iPhone 6s real device running iOS 12.0.1

**Comment by sjoerd0301** [comment]
Hi @dark-chocolate,

As position determination is never 100% accurate it may seem that you're moving.
I suggest you implement a margin between 0 and xx to catch minor speed changes when standing still.

We could implement that in the plugin, but since everyone wants to use different margins we chose not to.
So the implementation needs to happen on your side.

**Comment by dark-chocolate** [comment]
Thanks @sjoerd0301 , but why does it work in Android?

**Comment by mvanbeusekom** [comment]
Should have been fixed by now. I remember we had a bug with setting the speed parameter correctly in ios
