### ISSUE TITLE
Location Service Accuracy

### ISSUE THREAD

**Issue by pparadox11** [Baseflow/flutter-geolocator#267]
## 🏗 Enhancement Proposal

Location Service accuracy (on Android)

### Pitch

Well on Android we have 3 types of accuracy:
Gps, Network and High accuracy .

I was thinking about adding some functionality, so that someone can identify the current selection and maybe provide a stream to notify about changes.

My main concerns are the following:

1. Should we add all the options like:
   Gps, Network, High Accuracy, Off, Unknown (when the user hasn't granted permissions).
   or simply if the user has enabled 'High Accuracy' as the most common scenario

2. This one is more about the implementation:
    For a second stream, should the result coming back from the Android, be a map in this form => Map{type: String (position, location accuracy.. etc), data: Object} <=, or should a second event channel be created?

### Platforms affected
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@pparadox11 this looks like an interesting feature and would be useful for users on Android. So I am looking forward to a pull-request ;).

Regarding your questions:

To answer your first question, I think if we implement it we should implement all of the options. 

And regarding the second question, this depends a bit how we implement it. I currently see three options:

1. We return the location accuracy as part of the location update. So each time we get a location update from Android we also include the accuracy of the location update (as part of the `Position` object);
2. We create a method call that people can use to check the current available accuracy settings;
3. We create a new event channel which developers can subscribe to and get updates when the accuracy settings change.

I think we can implement all three options (al though I am not sure if option 3 is actually natively supported). Maybe we can start with implementing the first option which will already give developers a change to detect the current accuracy by looking into the position results being returned. What do you think?

**Comment by pparadox11** [comment]
Hi,

Hmm i am thinking about the case 1, maybe it's too much asking always about the location service accuracy? If you want to i can give it a try.

Case 2, yes of course.

Case 3, my main issue here is can we have 2 event channels? how we can distinguish that on the android  part?. As i have read the we have like 1 callback `onListen` but it doesnt give the channel name..?
About the part of location service accuracy change, we can register a broadcast receiver, but i dont know where and exactly we should unregister to avoid leaks.

I need some studying on my part ^^.

**Comment by audkar** [comment]
> Well on Android we have 3 types of accuracy: Gps, Network and High accuracy.

Isn't GPS == High accuracy? I think you are merging two different things into one bucket. There are:
- Sensors/providers (gps, cell networks, wifi, nfc, gyroscope).
- Quality groups. (high_accuracy, low_power, no_power)

Keep in mind that there also FusedLocationManager which uses much more providers then default one from android framework. That includes wifi, which improves init discovery speed and reduces battery usage tremendously.

On Android with each `Location` response you can get [accuracy](https://developer.android.com/reference/android/location/Location.html#getAccuracy()) and [provider](https://developer.android.com/reference/android/location/Location.html#getProvider()). In geoloactor [accuracy](https://pub.dev/documentation/geolocator/latest/geolocator/Position/accuracy.html) is already passed to Dart side. If you need `sensor` i think that can also be added to DAO object for exposing it on Dart side. 

> We create a new event channel which developers can subscribe to and get updates when the accuracy settings change.

I am not sure if you are talking about `sensors` or `quality groups`. 
- `quality group` doesn't change because it is requested by developer during location request API method call.
- `sensors` might be working in parallel. So when location updates are returned in sequence: Location1(network), Location2(network), Location3(gps), Location4(network). It doesn't mean that network switched to gps and back. Both providers works at the same time. Just one returns more data which matches applied filter.

Can you describe problem which you are trying to solve?

**Comment by pparadox11** [comment]
Hi,

The problem i want to solve, is what type of location accuracy has the user of the phone has choose.

High accuracy = All possible providers (wifi, mobile networks, gps)
Gps = only gps.
Battery saving = wifi, mobile network.

But this doesn't mean that if you get a position and you have enabled high accuracy, that you will get it as a high accuracy position, as many things can factor the output that moment.

Thats the problem i want to solve. not exactly the accuracy of the position, because that can factor from app to app, as want do you define a high accuracy position? 10, 15, 70 meters?

**Comment by GrahamDi** [comment]
Hi,

It would be very useful for my app if I was able to ensure the device used GPS only, in certain circumstances. There are situations when the location provided by WIFi is a completely different from the device's actual location eg. when the WiFi internet feed comes from a centralised server located somewhere else in the world.

Are you likely to add this feature to geolocator?

**Comment by JaMoLpE88** [comment]
I think it is a very interesting topic about being able to request to change the quality group, since precisely in the getCurrentPosition() method, if the device is not in high precision mode, the method returns nothing, no no response.  Until I have discovered that changing the energy-saving quality group to high precision, I have not solved the problem of the no response request and then it returns an answer.  Therefore, it would be VERY interesting to be able to request to change the quality group from the application and check whether or not it is in high precision and thus act accordingly.
