### ISSUE TITLE
New stream function for isLocationServiceEnabled

### ISSUE THREAD

**Issue by krishnaaro** [Baseflow/flutter-geolocator#330]
## 🚀 Feature Requests
i was expecting a stream function that returns boolean for isLocationServiceEnabled().
### Contextualize the feature
it fits in application like OLA, UBER, ...
if i missed any, please notify.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by StijnWoerkom** [comment]
@krishnaaro Do you mean something like this;

```
bool isLocationServiceEnabled() {
    if(isLocationServiceEnabled() == true) {
      print("Location Service is enabled");
    }
    return isLocationServiceEnabled();
  }
```

**Comment by krishnaaro** [comment]
@StijnWoerkom  yeah but not exactly.... i was looking for **Stream**, **Controller**, **listen**  for this isLocationServiceEnabled.....

**Comment by krishnaaro** [comment]
Any update ...!!!

**Comment by mvanbeusekom** [comment]
In verion 6.0.0 you will now receive a `LocationServiceDisabled` exception the moment the user disables the location services. Since the user needs to leave the App and comeback you can simply check again if location services are still enabled or not and act accordingly. There is no need to implement stream functionality (which will anyway be limited in it's use since you will have to keep you App running in the background to detect these changes, since the user needs to leave the App to update location service status).

**Comment by stpch** [comment]
What about disabling the location service through the status bar without leaving the app? I think there's no way to catch that as it happens when listening to the position stream?

![image](https://user-images.githubusercontent.com/1090696/92301855-82011380-ef67-11ea-9640-65818cce5de2.png)

**Comment by mvanbeusekom** [comment]
@stpch that is a good point, I always assumed this would also put your app into the `inactive` state and called `resume` when you go back to the App. I did some testing and it looks like this was a wrong assumption. 

I you require a stream to detect if location services are enabled or not I recommend adding a dependency to the "location_permissions" package and use the `LocationPermissions.serviceStatus` property to receive a stream. 

I will create a new enhancement issue to add this functionality to this plugin as well.

**Comment by aytunch** [comment]
@mvanbeusekom I am having the same issue.  A lot of Android users turn off location services through the status bar. And once they change the setting and close the status bar, they would want to see the change they made reflect to the UI. I have a lock icon showing the state of the `isLocationServiceEnabled`. And even when the user allows it, the icon does not change because `AppLifecycleState` can not catch the status bar interaction.  

I was very surprised that `AppLifecycleState` does not trigger when user opens that OS menu. I think this might be a shortcoming on  Flutter's side? If you think that is the case, I will open up an issue there. How can the `location_permissions`package get this info? can we do the same with this package and also `permission_handler` package?

**Comment by aytunch** [comment]
This is the Exception we get when user disables Location Services from the system tray menu as @stpch illustrates from the image.

When `PositionStream` is still subscribed to and when user disables Location Services this happens. And there is NO way I know of to understand user opened the system tray. So what should we do in order to not get this error?

Maybe something with `FocusNode`'s?

```
D/DecorView(26499): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@fdb185f[MainActivity]
D/ViewRootImpl[MainActivity](26499): windowFocusChanged hasFocus=true inTouchMode=true
D/ViewRootImpl[MainActivity](26499): windowFocusChanged hasFocus=false inTouchMode=true
E/flutter (26499): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: The location service on the device is disabled.
E/flutter (26499): #0      MethodChannelGeolocator._handlePlatformException
package:geolocator_platform_interface/…/implementations/method_channel_geolocator.dart:192
E/flutter (26499): #1      MethodChannelGeolocator.getPositionStream.<anonymous closure>
package:geolocator_platform_interface/…/implementations/method_channel_geolocator.dart:171
E/flutter (26499): #2      _invokeErrorHandler (dart:async/async_error.dart:16:24)
E/flutter (26499): #3      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:282:9)
E/flutter (26499): #4      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
E/flutter (26499): #5      _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (26499): #6      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (26499): #7      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
E/flutter (26499): #8      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
E/flutter (26499): #9      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
E/flutter (26499): #10     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:294:7)
E/flutter (26499): #11     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:132:11)
E/flutter (26499): #12     _ForwardingStream._handleError (dart:async/stream_pipe.dart:97:10)
E/flutter (26499): #13     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:161:13)
E/flutter (26499): #14     _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (26499): #15     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (26499): #16     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1013:7)
E/flutter (26499): #17     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:376:15)
E/flutter (26499): #18     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:394:16)
E/flutter (26499): #19     _DelayedError.perform (dart:async/stream_impl.dart:622:14)
E/flutter (26499): #20     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (26499): #21     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (26499): #22     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (26499): #23     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (26499): #24     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (26499): #25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (26499): #26     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (26499): #27     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (26499): #28     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (26499): #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (26499): #30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (26499): #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (26499):
D/DecorView(26499): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@fdb185f[MainActivity]
D/ViewRootImpl[MainActivity](26499): windowFocusChanged hasFocus=true inTouchMode=true
D/ViewRootImpl[MainActivity](26499): windowFocusChanged hasFocus=false inTouchMode=true

```
