### ISSUE TITLE
Listening Location Service and Permission Status

### ISSUE THREAD

**Issue by softronaut** [Baseflow/flutter-geolocator#348]
## 🚀 Feature Request

Provide a stream for device location service and application permission status.

In location feature intense applications, being notified by the instant state changes is very important. GeoLocator can check these states but it's a Future method as you know. I have to control states continuously, so what am I doing is creating a periodic stream for checking both state whole time.

This is a convenient solution but there are two concerns:
1 - Depends on the period, I have a delay
2 - Sending request to Native API continuously may be less performant instead being notified by changes only via stream.

If it's not possible, pardon me, I'm not expert at Native Android and iOS.

- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
In version 6.0.0 you will now receive a `LocationServiceDisabled` exception the moment the user disables the location services. Since the user needs to leave the App and comeback you can simply check again if location services are still enabled or not and act accordingly. There is no need to implement stream functionality (which will anyway be limited in it's use since you will have to keep you App running in the background to detect these changes, since the user needs to leave the App to update location service status).
