### ISSUE TITLE
placemarkFromCoordinates doesn't provider a proper address. How can i get proper address from placeMark?

### ISSUE THREAD

**Issue by tareq3** [Baseflow/flutter-geolocator#421]
## 💬 Questions and Help

For questions or help we recommend checking:

- The [Flutter tag in Stack Overflow](https://stackoverflow.com/questions/tagged/flutter)

**Comment by mvanbeusekom** [comment]
Closing due to lack of details. Interesting information would be:

- Which coordinates are you requesting;
- What are you expecting;
- What do you receive;
- Which platform are you using;
- What version of Flutter and Geolocator are you on.

Also you might want to have a look at issues #431 and #427
