### ISSUE TITLE
[iOS] Allow users to explicitly enable support for background location updates

### ISSUE THREAD

**Issue by mvanbeusekom** [Baseflow/flutter-geolocator#423]
## 🏗 Enhancement Proposal

Currently on iOS background location updates are enabled by default and cannot be turned off. This might result into Apple rejecting a submitted app because it the developer doesn't need support for background location updates and thus didn't specify any justification for this.

### Pitch

The pitch is basically to apply the following two changes:

1. Make sure that by default the support for background location updates is disabled;
2. Allow for users of the Flutter API to specify an optional parameter which enables support for background location updates.

The iOS background location updates are configured at the following location: https://github.com/thomasnilsson/flutter-geolocator/blob/bf10519e41a98a70f66edfcb1de511521d938672/ios/Classes/Tasks/LocationTask.m#L39

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [ ] :robot: Android

**Comment by ramsestom** [comment]
This issue also concerns android. 
Since android API level >=29 you have to allow android.permission.ACCESS_BACKGROUND_LOCATION permission for background locations to work.

**Comment by severance88** [comment]
Just yesterday I had my app rejected on the App Store.

I had to fork the repo and remove/change a couple of lines.

`Info.plist` inside `example/ios` folder:

removed
`<key>UIBackgroundModes</key>
	<array>
		<string>location</string>
	</array>`

And in the plugin folder `ios/Classes/Tasks/LocationTask.m`:

removed 
`_locationManager.allowsBackgroundLocationUpdates = YES;`

So the app was being rejected specifically because of the example project `Info.plist`

 [The commit that changed this](https://github.com/Baseflow/flutter-geolocator/commit/9d2d9c6ec9b2b0ccbf68fbb2fe824c4ecc6e22f6)

**Comment by mvanbeusekom** [comment]
I just released version 5.3.2+2 of the Geolocator which adds support for this issue. More details can be found in the [README.md](https://github.com/Baseflow/flutter-permission-handler/edit/develop/README.md) file.
