### ISSUE TITLE
No "locality" is retrieved from coordinates but "name", "thoroughfare", "postalCode" and "country" are

### ISSUE THREAD

**Issue by olivierpicault** [Baseflow/flutter-geolocator#433]
## 🐛 Bug Report

No `locality` is retrieved from coordinates lat:51.531301199999994, lon: -0.0956268 but `name`, `thoroughfare`, `postalCode` and `country` are.

![Capture d’écran 2020-05-08 à 16 18 41](https://user-images.githubusercontent.com/4429956/81414674-a1b63580-9147-11ea-87be-fc03119030e4.png)

Coordinates have been retrieved this way:
```
Position pos = await Geolocator()
    .getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
```

### Expected behavior

A `locality`, here it should be "London" or "Londres" in French, should be retrieved. 

### Reproduction steps

```
Position pos =
    Position(latitude: 51.531301199999994, longitude: -0.0956268);

List<Placemark> placemarks = await Geolocator().placemarkFromPosition(pos);

print(placemarks[0].locality);
print(placemarks[0].name);
print(placemarks[0].thoroughfare);
print(placemarks[0].postalCode);
print(placemarks[0].country);
```

### Configuration

geolocator: ^5.3.0

**Version:** Flutter 1.12.13+hotfix.9

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by olivierpicault** [comment]
Hi guys, do we have any update here ? Thanks

**Comment by mvanbeusekom** [comment]
As of version 6.0.0 the geocoding features are no longer part of the geolocator plugin. Instead we have moved them into there own plugin called [geocoding](https://pub.dev/packages/geocoding). 

I did a test and indeed noticed that on Android the locality is not returned. Seems like Google (through the [Android geocoder SDK](https://developer.android.com/reference/android/location/Geocoder)) simply doesn't return any value here:

```
iOS:
- Name: 30 Wharf Road,
- Street: 30 Wharf Road,
- ISO Country Code: GB,
- Country: United Kingdom,
- Postal code: N1 7GR,
- Administrative area: England,
- Subadministrative area: London,
- Locality: London,
- Sublocality: Islington,
- Thoroughfare: Wharf Road,
Subthoroughfare: 30

Android:
- Name: 36,
- Street: 36 Wharf Rd,
- ISO Country Code: GB,
- Country: United Kingdom,
- Postal code: N1 7GR,
- Administrative area: England,
- Subadministrative area: Greater London,
- Locality: ,
- Sublocality: ,
- Thoroughfare: Wharf Road,
- Subthoroughfare: 36
```

Unfortunately this is not something I can influence, since we simply rely on the data returned from the Android API. We do however plan to implement also additional providers (like HERE or Google Maps) but these will be paid services and you most likely could just as easily implement there plugins directly. For now I will close this ticket, but feel free to open a new ticket on the [geocoding](https://github.com/baseflow/flutter-geocoding/issues) plugin if you have a possible direction we can look for a solution or simply want to continue the discussion.
