### ISSUE TITLE
That is my error: Unhandled Exception: PlatformException(ERROR_GEOCODING_ADDRESS, grpc failed, null)

### ISSUE THREAD

**Issue by danielshongo** [Baseflow/flutter-geolocator#440]
that is my code:

void sendRequest(String intendedLocation) async{
      List<Placemark> placemark = await Geolocator().placemarkFromAddress(intendedLocation);
      double latitude = placemark[0].position.latitude;
      double longitude = placemark[0].position.longitude;
      LatLng destination = LatLng(latitude, longitude);
      _addMarker(destination, intendedLocation);
      String route = await _googleMapsServices.getRouteCoordinates(_initialPosition, destination);
      CreateRoute(route);
  }

help me please,  brother

**Comment by BeneBr** [comment]
I have the same error.
Here is my code.

Future<void> _destinationMarker(String _destinationAddress) async{
    List<Placemark> placemark = await Geolocator().placemarkFromAddress(_destinationAddress);
    setState(() {
      _destinationPosition = placemark[0].position;
    });
    Marker sourceMarker = Marker(
      markerId: MarkerId("destinationMarker"),
      position: LatLng(_destinationPosition.latitude, _destinationPosition.longitude),
      infoWindow: InfoWindow(
        title: "Endereço de Destino",
        snippet: "Posicione o Endereço de Entrega"
      )
    );
    LatLng destiny = LatLng(_destinationPosition.latitude, _destinationPosition.longitude);
    await _mapController.moveCamera(CameraUpdate.newLatLngZoom(destiny, 17));
      
    setState(() {
      _markers.add(sourceMarker);
      _activeConfirmDelivery = true;
      _stackSource = true;
    });
  }

**Comment by mvanbeusekom** [comment]
This issue is thrown by Android is self and as far as I know could have two reasons:

1. The Google Play Services are blocked (which could happen in certain countries where special restrictions apply);
2. Request to the Android Geocoder backend are rate limited, in case this limit is reached you also receive this exception. 

Unfortunately I am having a hard time to finding exact numbers as to what the rate limit is and when would you reach it.

I am however working on improvements that would allow you to check if the Android Geocoder SDK is available and give more developer friendly feedback on it so you can better inform your users about the availability of this feature.

I am also working on a solution to integrate premium geocoding features (like the Google Maps API or the HERE API) into the plugin, these will of course only work when you have a valid license.
