### ISSUE TITLE
geocoding: Placemark behaves differently on iOS and Android

### ISSUE THREAD

**Issue by nincode** [Baseflow/flutter-geolocator#448]
## 🐛 Bug Report

placemarkFromCoordinates behavior differs between iOS and Android.
Placemark name on Android has the street number, while on iOS it contains both the street number and the street name.
 
**iOS**
Placemark name: Ulica Stojana Protica 29
Placemark thoroughfare: Ulica Stojana Protica
Placemark locality: Belgrade

**Android**
Placemark name: 1
Placemark thoroughfare: Stojana Protica
Placemark locality: Belgrade

### Expected behavior
Expected both platforms to return data in the same format.

### Reproduction steps
List<Placemark> placemark = await Geolocator().placemarkFromCoordinates(geo.latitude, geo.longitude);
for (var pm in placemark) {
  locationString += pm.name + '|' + pm.thoroughfare + '|'+pm.locality;
}
### Configuration

**Version:** 5.3.1

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@nincode this behaviour is because we use the local geocoding API of the platform. This means that on iOS the Apple Maps services are used (through the [CLGeocoder](https://developer.apple.com/documentation/corelocation/clgeocoder) API) and on Android devices the Google Maps services are used (using the [Geocoder](https://developer.android.com/reference/android/location/Geocoder) API).

Unfortunately the details per service differ a bit which explains the diferences you might experience when comparing output cross platform.
