### ISSUE TITLE
Sample code for error handling?

### ISSUE THREAD

**Issue by giorgio79** [Baseflow/flutter-geolocator#456]
Hello,

Could you give some sample code for error handling?
### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by renefloor** [comment]
Did you encounter any error that you didn't know how to handle?

**Comment by giorgio79** [comment]
Eg
E/flutter ( 8816): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ERROR_GEOCODING_COORDINATES, grpc failed, null)
E/flutter ( 8816): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 8816): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)

**Comment by mvanbeusekom** [comment]
@giorgio79 this error is caused by Android's Geocoding not being able to reach the backend service to translate the coordinates (if you search the issues for the exception you will find others asking the same question). 

There can be several caused (in order of most likely):

1. Geocoding services require an active internet connection. When there is no connection available you might get this error;
1. The Android Geocoding services are limited in there functionality (rate limited). This means if you do to many requests within a certain time period you'll get blocked (which results in this exception);
2. The Geocoding services require Android Play Services, in some countries these services are blocked by goverment firewalls. This means Android's Geocoding backend services can not be reached, which result in this error;
3. The Geocoding backend services are down and cannot be reached;
