### ISSUE TITLE
How does the method "placemarkFromCoordinates" & "placemarkFromAddress" internally works?

### ISSUE THREAD

**Issue by bajajsahil** [Baseflow/flutter-geolocator#467]
As per my understanding, usually we have Google APIs to get the location information based on coordinates or address. So, how does this library gets the information without API? Or, it internally uses any API?

This is just a question which might have a very simple answer and I am just looking for that :)

Thanks in advance,

**Comment by mvanbeusekom** [comment]
Hi @bajajsahil,

That is here not any different. The geocoding features use the default APIs on the device to handle the translation.

This mean on iOS the plugin uses the `CLGeocoder` SDK, which internally makes a call to the Apple Maps API. On Android the plugin uses the Android `Geocoder` class (part of the Google Play Services), which internally makes use of the Google Maps API.

These APIs are free to use but have limitations to there use. Both are rate limited which means you can only do a x amount of request in a certain time period, when you do more you will receive an error. I don’t know the exact values since Apple and Google are not very clear about them in their documentation.

Hope this answers helps. More information can be found when searching the Net for those SDKs I mentioned.

**Comment by bajajsahil** [comment]
Hi @mvanbeusekom,

Thanks for the answer. Appreciate it.

One suggestion though, it would be really helpful if you put this information in plugin readme so that people can handle the error gracefully if the quota exceeds. I think many of us aren't aware of this.

Also, if I or someone found the exact quota limit then it will be good to share with everyone.

Thanks.
