### ISSUE TITLE
No PlatformException for PermissionStatus.disabled in the new version (^5.3.2+2)

### ISSUE THREAD

**Issue by aashitgarodia** [Baseflow/flutter-geolocator#475]
## 🔙 Regression

< If location is disabled then `await Geolocator().getCurrentPosition(...)`  takes forever it doesn't throw any PlatformException.
I'm really new to this coding world, please let me know if I've made any mistakes would really mean a lot!.
--->

### Old (and correct) behavior
In the old version (^3.0.1) in the geolocator.dart (_line: 193_) there **_is_** exception thrown for else if (permission == PermissionStatus.disabled)

### Current behavior
In the new version (^5.3.2+2) in the geolocator.dart (_line: 213_) there **_is no_** exception thrown for else if (permission == PermissionStatus.disabled)

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@aashitgarodia, we have revised how permissions work. Since both iOS and Android guidelines advise developers to allow users to give permissions to access the device's location even when the location services are not enabled. 

This meant we no longer could have the `disabled` status as part of the `PermissionStatus` enum. That is why we created a separate method which allows you to check if the location services are enabled or not instead of being part of the permission system. An example would be:

```dart
final geolocator = Geolocator();
final isEnabled = await geolocator.isLocationServiceEnabled();

if (isEnabled) {
  final position = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
  print('Current position: ${position.toString()}');
}
```

Unfortunately our documentation was not updated accordingly and still mention the old `PermissionStatus.disabled`.This has been fixed and will be released soon so pub.dev will also so the correct documentation. For now you can check it on Github: https://github.com/Baseflow/flutter-geolocator/blob/develop/README.md.

**Comment by aashitgarodia** [comment]
Thank you so much!
