### ISSUE TITLE
getCurrentPosition Without enable location services  both foreground and background

### ISSUE THREAD

**Issue by Sachinsowri** [Baseflow/flutter-geolocator#495]
## 💬 Questions and Help

For questions or help we recommend checking:

- The [Flutter tag in Stack Overflow](https://stackoverflow.com/questions/tagged/flutter)

i use android 10(sdk 29)  and geolocator: ^6.0.0+1  version 

it works fine while location service enabled  ..

but location service disabled  .. when i call getCurrentPosition throw exception "Location service not enabled .." 

if there is any way(in background) to getCurrentPosition  Without enable location services ...

**Comment by mvanbeusekom** [comment]
No, the SDKs on both platforms (iOS and Android) need the Location Services to be enabled otherwise they will not return location information. 

This is a privacy feature which allows users to protect their privacy and prevents Apps to acquire location information when the user doesn't want to. So when the Location Services are disabled we will throw an exception which you can catch and handle accordingly (i.e. when running in the foreground you can show a dialog asking the user to enable the location services or if you are running in the background you could stop fetching the location and maybe set a setting somewhere so the App knows to ask the user to enable the Location Services next time it moves to the foreground).
