### ISSUE TITLE
[6.0.0+1] location_options.dart 'accuracy' property

### ISSUE THREAD

**Issue by GrahamDi** [Baseflow/flutter-geolocator#501]
## 🐛 Bug Report

The LocationOptions model defines an 'accuracy' property, which is the property name originally. The equivalent property in the methods in geolocator.dart is expected as 'desiredAccuracy'. This mismatch is causing problems when calling these methods with a predefined LocationOption instance.

LocationOptions model should define 'desiredAccuracy'.

**Comment by mvanbeusekom** [comment]
@GrahamDi thank you for taking the time to write. However it is not really clear to me why this is a problem (except from not being very consistent)?

The geolocator methods don't allow you to build a `LocationOptions` instance and theoretically this class can even be made private since it is only used internally. You mention you are calling the geolocation methods with a predefined instance of the `LocationOptions` class, but the methods really don't accept a `LocationOptions` class, hence that I don't really understand why this should be a problem. Could you elaborate?

**Comment by GrahamDi** [comment]
Hi Maurits,

Thanks for the rapid response.

Rightly or wrongly, my code for version 5.3.2+2 looked like the following (code snippet but you can see the definition of the LocationOptions instance and its use in the getPositionStream method. No syntax errors and all working fine.

When upgrading to 6.0.0+1 the new getPositionStream method complained of 0 positional arguments expected but 1 found.

```
     _locationOptions = LocationOptions(
        accuracy: globals.configFromDatabase.locationAccuracy,
        distanceFilter: globals.configFromDatabase.locationDistance,
        // Checks every 'locationTime' milliseconds.
        timeInterval: globals.configFromDatabase.locationTime,
      );
      var _deviceHasLocationAccess = await checkLocnAccess(
        context,
        calledFrom: CalledFrom.sailorsPage,
      );
      if (_deviceHasLocationAccess) {
        _positionStream = _geolocator
            .getPositionStream(_locationOptions)
            .listen((position) async {
```
I got around the error by moving the contents of the LocationOptions definition into the getPositionStream method parameters and renaming 'accuracy' to 'desiredAccuracy'.

**Comment by mvanbeusekom** [comment]
Hi @GrahamDi,

That is correct indeed, this is one of the breaking changes in the new 6.0.0 API. Instead of passing around the `LocationOptions` (and initializing it everytime) you can now simply assign the parameters directly to the `getPositionStream` method. So the method signature changes from:

``` dart
Stream<Position> getPositionStream([
  LocationOptions locationOptions = const LocationOptions(), 
  GeolocationPermission locationPermissionLevel = GeolocationPermission.location,
])
```

to:

```dart
Stream<Position> getPositionStream({
  LocationAccuracy desiredAccuracy = LocationAccuracy.best,
  int distanceFilter = 0,
  bool forceAndroidLocationManager = false,
  int timeInterval = 0,
  Duration timeLimit,
})
```

So there is also no need to specify a permission level anymore since the plugin will now be able to figure it out by looking at the specified permission in de AndroidManifest.xml (Android) or Info.plist (iOS). Meaning I had to update the signature anyway and decided to do it this way making it more inline with how Flutter in general treats parameters.

Does this answer/ solve your issue?

**Comment by GrahamDi** [comment]
Thanks Maurits. That makes sense.
