### ISSUE TITLE
Note: geolocator-6.0.0+1\android\src\main\java\com\baseflow\geolocator\location\LocationManagerClient.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by inceptusp** [Baseflow/flutter-geolocator#502]
## 🔙 Regression

The previous version of Geolocator didn't had this warning

### Reproduction steps

Just compile an app with the new plugin or compile an existing app after a ```flutter clean```

### Configuration

**Version:** 6.0.0+1

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

### Aditional info

It seems that the problem could be ```LocationProvider.AVAILABLE``` as Android Docs says: "Location provider statuses are no longer supported."

**Comment by mvanbeusekom** [comment]
Hi @inceptusp, I have just released version 6.0.0+2 of the geolocator which removes the deprecation warning. 

The warning was generated because we implemented the `LocationListener.onStatusChanged` method for backwards compatibility reasons. Since this method will not be invoked from Android Q and later this will not be causing any problems, hence we simply suppressed the deprecation warning.
