### ISSUE TITLE
getLastKnownPosition() doesn't check for LocationService

### ISSUE THREAD

**Issue by humazed** [Baseflow/flutter-geolocator#514]
## 🐛 Bug Report

when calling `getLastKnownPosition()` while the LocationService is disabled the location always returns null, so I guess the lib should check for it and ask the user to activate it as you do with the other methods if it returns null.
### Configuration

**Version:** 6.0.0+3

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
This is on purpose since disabling the location services will clear the location cache. So having logic to enable the service will not help since the cache will still be empty and you will still receive `null`. More information can be found here: https://developer.android.com/training/location/retrieve-current#last-known
