### ISSUE TITLE
Speed issues with version 6

### ISSUE THREAD

**Issue by mulderpf** [Baseflow/flutter-geolocator#515]
## 🔙 Regression

I just updated to version 6.0.0+2 from 5.3.2+2 and I noticed a significant slow-down on Android 11 with the AndroidLocationManager set to on.  I also tested it on Android 7 to see if I was imagining things and ended up running a few tests and the performance in general is worse now.

It appears that the new version now needs the GPS to "warm up" as the first calls in all my tests took around 10 seconds to complete.

In this state, this library is not suitable for me to use in production.

AndroidLocationManager set to false, the behaviour isn't too bad, but it is definitely worse the previous library.  For users who have this set to true, it performs significantly worse than before.

Apologies for all the stats, but just wanted to make sure I thoroughly tested this before reporting it.

### Old (and correct) behavior (version 5.3.2+2)

Android 11 on a Pixel 2 - 5 repeated calls (with AndroidLocationManager = false): 1.46 seconds on average
Android 11 on a Pixel 2 - 5 repeated calls (with AndroidLocationManager = true): 0.005 seconds on average

Android 7 on a Samsung S6 Edge - 5 repeated calls (with AndroidLocationManager = false): 0.0166 seconds on average
Android 7 on a Samsung S6 Edge - 5 repeated calls (with AndroidLocationManager = true): 0.0445 seconds on average

Android 6.0.1 on a Samsung S2 - 5 repeated calls (with AndroidLocationManager = false): 0.267 seconds on average (0.12 if I ignore the "warm-up"/first call)
Android 6.0.1 on a Samsung S2 - 5 repeated calls (with AndroidLocationManager = true): 0.029 seconds on average (0.009 seconds if I ignore the "warm-up"/first call).

### Current behavior (version 6.0.0+2)

Android 11 on a Pixel 2 - 5 repeated calls (with AndroidLocationManager = false): 1.26 seconds on average (slightly better!) - (1.22 if I ignore the "warm-up"/first call)
Android 11 on a Pixel 2 - 5 repeated calls (with AndroidLocationManager = true): 4.3 seconds on average (significantly and noticably worse!) - (2.67 if I ignore the "warm-up"/first call)

Android 7 on a Samsung S6 Edge - 5 repeated calls (with AndroidLocationManager = false): 2.715 seconds on average (0.83 if I ignore the "warm-up"/first call)
Android 7 on a Samsung S6 Edge - 5 repeated calls (with AndroidLocationManager = true): 2.7 seconds on average (0.485 if I ignore the "warm-up"/first call)

Android 6.0.1 on a Samsung S2 - 5 repeated calls (with AndroidLocationManager = false): 0.907 seconds on average (0.33 if I ignore the "warm-up"/first call)
Android 6.0.1 on a Samsung S2 - 5 repeated calls (with AndroidLocationManager = true): 4.194 seconds on average (3.71 seconds if I ignore the "warm-up"/first call).

### Reproduction steps

I measure how long it took for 

`    gl.Position p = await gl.getCurrentPosition(
        forceAndroidLocationManager: forceAndroidLocationManager);`

to return a value.

### Configuration

**Version:** 6.0.0+2

**Platform:** 
Android only - I didn't notice a slowdown on iOS, but didn't test either.

**Comment by mvanbeusekom** [comment]
Hello @mulderpf, 

Thank you for the extensive report and testing you did, I really appreciate it and of course would really like to improve performance when possible. 

You mention that the main performance difference is when running the `getCurrentPosition` with the `forceAndroidLocationManager` set to `true`. In this case I actually solved a bug that I noticed in version 5.x of the geolocator. Namely in this version we always returned the last known location instead of the actual location of the device. This is why the method always returned very fast because it simply returned the location from the location cache, however it is very likely that this is not the best possible location. Here is a snippet containing the bug:

```java
  @Override
  public void startTask() {

    LocationManager locationManager = getLocationManager();

    // Make sure we remove existing listeners before we register a new one
    locationManager.removeUpdates(this);

    // Try to get the best possible location provider for the requested accuracy
    mActiveProvider = getBestProvider(locationManager, mLocationOptions.getAccuracy());

    if (Strings.isEmptyOrWhitespace(mActiveProvider)) {
      handleError();

      return;
    }

    mBestLocation = locationManager.getLastKnownLocation(mActiveProvider);

    // If we are listening to multiple location updates we can go ahead
    // and report back the last known location (if we have one).
    if (mStopAfterFirstLocationUpdate && mBestLocation != null) {
      reportLocationUpdate(mBestLocation);
      return;
    }

    Looper looper = Looper.myLooper();
    if (looper == null) {
      looper = Looper.getMainLooper();
    }

    locationManager.requestLocationUpdates(
        mActiveProvider,
        mLocationOptions.getTimeInterval(),
        mLocationOptions.getDistanceFilter(),
        this,
        looper);
  }
``` 

In this case you call the `getCurrentPosition` method the `mStopAfterFirstLocationUpdate` parameter is always set to `true`. So this code will then return the result of the `mBestLocation` which is the outcome of the `locationManager.getLastKnownLocation(mActiveProvider)` call. 

In the new version (6.0.0) I have fixed this bug and ensured that the `getCurrentPosition` method returns the actual location of the device (acquired from the necessary sensors). This however indeed takes some time the first time you make the call (since the devices needs to connect to satellites, triangulate the position based on cell-towers and possible request location information from the WiFi signal, etc...).

Let me know if this explains the results you are noticing?

**Comment by mulderpf** [comment]
Thank you - this might also explain a few angry reviews people have left (not too many!!) for the app picking up the wrong location.  OF course when testing, it always works as I tend to test in the same spot!  Thank you.

**Comment by mvanbeusekom** [comment]
Thank you @mulderpf for letting me know.
