### ISSUE TITLE
using this package with "google_maps_place_picker" package

### ISSUE THREAD

**Issue by 00AhmedMokhtar00** [Baseflow/flutter-geolocator#533]
The code and library were working fine, but when I tried to add the [google_maps_place_picker](https://pub.dev/packages/google_maps_place_picker) the geolocator code showed an error:

`"error: The method 'Geolocator' isn't defined for the type 'HomePageState'. (undefined_method at [xxx] lib/Page/HomePage.dart:676)"`

code:

```
await Geolocator().placemarkFromCoordinates(lat, lng).then((result) {
        setState(() {
          contFrom.value =
              new TextEditingValue(text: result[0].administrativeArea);
          pickAddress = contFrom.text;
          dataPick['Lat'] = lat;
          dataPick['Lng'] = lng;
        });
```
I'm using: 

geolocator: ^6.0.0+4
google_maps_place_picker: ^0.10.0

**Comment by mvanbeusekom** [comment]
@00AhmedMokhtar00 you mentioned you are using version 6.0.0+4 of the geolocator plugin. It looks like you have also update the geolocator plugin. 

Since version 6.0.0 we have removed the geocoding features to it's own plugin called [geocoding](https://pub.dev/packages/geocoding). Meaning the geolocator no longer contains the `placemarkFromCoordinates` and `placemarkFromAddress` methods. If you don't use any of the other features of the geolocator plugin (e.g. acquiring the current location of the device) I would suggest to replace the `geolocator: ^6.0.0+4` plugin with the `geocoding: ^1.0.4` plugin, and update your code to:

```dart
await placemarkFromCoordinates(lat, lng).then((result) {
        setState(() {
          contFrom.value =
              new TextEditingValue(text: result[0].administrativeArea);
          pickAddress = contFrom.text;
          dataPick['Lat'] = lat;
          dataPick['Lng'] = lng;
        });
```
