### ISSUE TITLE
Example on pub.dev is misleading. Needs to display code having the proper Geolocator plugin import

### ISSUE THREAD

**Issue by Sakshi725744** [Baseflow/flutter-geolocator#547]
### Pitch

The given example on pub.dev is not portraying the example carrying the import for the plugin, i.e. import 'package:geolocator/geolocator.dart'; is nowhere added making the documentation having uncertainties. I myself faced this confusion when i came across the example page and hence "main.dart" folder needs modifications.

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by Sakshi725744** [comment]
I would like to volunteer for this issue

**Comment by mvanbeusekom** [comment]
Looking forward to your PR!

**Comment by icelab-uki** [comment]
Totally agree the example not include the presented library.
And it's full of unknown error.

I tried to run
Position newPosition = await Geolocator.getCurrentPosition();

But it keep saying
MissingPluginException(No implementation found for method isLocationServiceEnabled on channel

Really frustated

**Comment by pp2015jp** [comment]
Totally agree the example not include the presented library.
And it's full of unknown error.

I tried to run
Position newPosition = await Geolocator.getCurrentPosition();

But it keep saying
MissingPluginException(No implementation found for method isLocationServiceEnabled on channel

Really frustated

**Comment by mvanbeusekom** [comment]
I have been looking into this and the problem is that pub.dev only shows the code in the `example/lib/main.dart` file.

Our accompanying example app however has a much more detailed example with multiple code files showing different approaches (using `getLastKnownPosition` and `getPositionStream` for example).

So if you are looking for examples please open the complete example app and look a bit further then simple the "Example" tab on pub.dev.

Regarding the other error you are receiving, if you are on Android make sure you update your gradle version. If you want more help I'd suggest opening a separate issue.

**Comment by pp2015jp** [comment]
Thank you very much for your reply.
But the example is not runnable.
And it is difficult for me to follow because it uses
"FutureBuilder(
      future: Geolocator.getLastKnownPosition(),
..."
But I did not use FutureBuilder in my work.

I only need to know how to get location as a variable, which is suppose to be done easily by
"Position position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);"
as written on https://pub.dev/packages/geolocator

But it's not true. I faced many errors and it already took me almost two whole days, just to get simple location data.

Here are examples of error

1.
MissingPluginException(No implementation found for method checkPermissionStatus on channel com.baseflow.flutter/location_permissions)

2.
Instance member 'getCurrentPosition' can't be accessed using static access.

3.
      > Could not open proj generic class cache for build file 'S:\Flutter\Study3\flutter-geolocator-develop\geolocator\example\android\app\build.gradle' (C:\Users\User1\.gradle\caches\5.6.2\scripts\y2lvp1z9nqdoybt9o7gos3uy\proj\proj9d9bdfa13168004751655a79e56a065e).
         > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 57




I previously use old version of Geolocator before.
More lines of code, but much more easier to use

**Comment by mvanbeusekom** [comment]
@pp2015jp your problem is most likely caused by a faulty cache which is mixing up version 6.x and the previous versions of the geolocator plugin. 

Errors 1 and 2 and 4 are referring to the the old version of the plugin. While error number 5 is indeed referring to the last version. Please make sure you clean your project using `flutter clean` in the root of your application and try to build again. 

If you keep on receiving the error you mentioned in point 5, make sure you update your gradle version. Details can be found here: https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-Gradle-4.1-and-Android-Studio-Gradle-plugin-3.0.1

**Comment by pp2015jp** [comment]
Thank you very much for your clarification.
I'm not sure about the cause of error.
But after I test with new blank project, it seems to work.
I'll check what happen later.

p.s. clean couldn't help

**Comment by mvanbeusekom** [comment]
Thanks to @Sempakonka who restyled the example App so all logic fits nicely in the `main.dart` making the example shown at https://pub.dev/packages/geolocator/example much more useful.

Also thanks to all people reporting this issue.
