### ISSUE TITLE
what happens to events when subscription to location is paused

### ISSUE THREAD

**Issue by smolugu** [Baseflow/flutter-geolocator#549]
Hi,

I am pausing location stream when the device is moving above a certain speed limit and resuming the stream after the speed
decreases below a certain speed limit.

Would like to know what happens to the location events when the stream is paused. will new events be buffered or stopped?

Regards,
Shyam

**Comment by mvanbeusekom** [comment]
Hi @smolugu,

According to the [StreamController](https://api.dart.dev/stable/2.10.2/dart-async/StreamSubscription/pause.html) documentation events will be buffered and delivered when the stream is resumed. 

Since the communication from the Dart to the Native platform uses a broadcast stream, the underlying platform stream doesn't receive any pause signal and will keep on emitting events. 

If you want to stop emitting events on the native platform as well, I'd suggest you cancel the subscription and start listening to a new subscription again at some point.

Hopes this helps, if not let me know, I can reopen the issue if necessary.

**Comment by smolugu** [comment]
Ok. Thank you!

Does pausing the stream has an effect on battery usage? I don't need events in between pause and resume. Once the stream is resumed I only need fresh events.

What do you suggest in this case? Cancel or Pause and resume when needed?

Regards,
Shyam

**Comment by mvanbeusekom** [comment]
I would definitely cancel in this case. 

As the native side (iOS or Android) will keep on tracking location changes and sending them to the Dart side. Dart will simply buffer them till the stream is resumed. So battery usage will still be the same.

**Comment by smolugu** [comment]
ok then I will cancel and start when needed. Thank you! Really appreciate your inputs.

**Comment by bhanuka96** [comment]
@smolugu and @mvanbeusekom how do I cancel and start it again?

**Comment by mvanbeusekom** [comment]
@bhanuka96 when you call `listen` on the stream returned from the `getPositionStream` method you will receive an instance of the `StreamSubscription` class. You can stop/cancel your stream by calling `cancel` on this instance:

```dart
final subscription = Geolocator.getPositionStream().listen((position) => print(position));

// Stop/ cancel receiving position updates
subscription.cancel();
...

**Comment by bhanuka96** [comment]
@mvanbeusekom Thank you. I tried this. can you please check this https://github.com/Baseflow/flutter-geolocator/issues/596

**Comment by bhanuka96** [comment]
I got this error when I start stream, `I/Timeline(18078): Timeline: Activity_idle id: android.os.BinderProxy@d60d5c time:39082992`

in  case AppLifecycleState.resumed:

**Comment by bhanuka96** [comment]
now I am using below method instead of steam. Is there any issue?

```
  void initLocation(){
    _lifeCycleTimer2 = Timer.periodic(Duration(seconds: 1), (Timer t) async {
      await locationService.getLocation().then(getLocation);
    });
  }
```
