### ISSUE TITLE
TimeoutException after 0:00:00.000000: Future not completed

### ISSUE THREAD

**Issue by bhanuka96** [Baseflow/flutter-geolocator#567]
I got this error `TimeoutException after 0:00:00.000000: Future not completed` after update to `6.1.2`. (I am not sure I got the same error before update the plugin). 

`LocationModel _userLocation = await locationService.getLocation();//return null with timeout exception`

My Gps service class

```
class LocationService {
  LocationModel _currentLocation;

  BehaviorSubject<LocationModel> _locationController = BehaviorSubject<LocationModel>();

  Stream<LocationModel> get locationStream => _locationController.stream;

  void initLocation() {
    Geolocator.requestPermission().then((value) {
      if (value == LocationPermission.whileInUse || value == LocationPermission.always) {
        Geolocator.getPositionStream(desiredAccuracy: LocationAccuracy.bestForNavigation, distanceFilter: 0, timeInterval: 1000).listen((event) {
          if (event != null) {
            _locationController.add(LocationModel.fromGeoLocatorData(event));
          }
        });
      }
    });
  }

  Stream<LocationModel> getLocStream() {
    return locationStream;
  }

  Future<LocationModel> getLocation() async {
    try {
      Position userLocation = await Geolocator.getCurrentPosition();
      _currentLocation = LocationModel.fromGeoLocatorData(userLocation);
    } on Exception catch (e) {
      print('Could not get location: $e');
    }
    return _currentLocation;
  }
}

```

**Comment by mvanbeusekom** [comment]
Hi @bhanuka96, this was caused by a mistake on my end which I corrected this morning. I have released an update of the `geolocator_platform_interface` package (v1.0.6+1) which includes the fix. To fix this you might need to run `flutter pub get` to update your packages. After that this issue should be solved and the timeout settings should be respected:

1. If the `timeLimit` parameter is not supplied, no timeout will occur and the `getCurrentPosition` method will wait until it receives the first location;
2. If a `timeLimit` is supplied the `getCurrentPosition` will throw a `TimeoutException` when the time limit is reached before a location is returned.

Apologies for the inconvenience.

**Comment by ankit-roy-greenway** [comment]
Hi @mvanbeusekom 

First of all, thank you very much for this package.
I am facing this same error. But in my case, this error is raised only when the user first time gives access of the location. Once it raised this timeout error, next time it works perfectly. Any idea?

**Comment by Faiizii** [comment]
Where to catch `TimeoutException`?

**Comment by ferrarafer** [comment]
Same here. How do I catch the TimeoutException?

**Comment by SachinKumarErnd** [comment]
I am facing this issue when fetching location in background mode , in foreground its working fine
