### ISSUE TITLE
GPS enabled and disabled dynamic detection

### ISSUE THREAD

**Issue by zubers1128** [Baseflow/flutter-geolocator#573]
Geolocator().isLocationServiceEnabled() is not checking if the GPS is enabled or not and if we disable the GPS from notification bar. It is not detecting that also.

**Comment by mvanbeusekom** [comment]
Hi @zubers1128, 

Thank you for reporting this issue. Would you mind providing a bit more information? Questions I have are:

1. Which version of the  plugin are you using? Since version 6.1.1 we introduced an enhancement where the position stream received from the`getPositionStream` method will return a `LocationServiceDisabledException` when the location services are switched of via the notification bar while listening to the stream. Of course this exception is also returned when you start listening or when calling the `getLastKnownPosition` or `getCurrentPosition` methods;

2. If the above won't help, could you elaborate on your application flow? When in your application flow are you checking the location service availability?

**Comment by zubers1128** [comment]
The version of the plugin I am using is 6.1.3. I was not able to get the LocationServiceDisabledException on GPS disable, it only worked when the location was disabled from the settings and not from the notification bar, what I did try was use a combination of the getPositionStream , getCurrentPosition and AppLifeCycle state to get the desired result. However it would be great if the plugin could auto-detect the GPS going into any other mode except high_accuracy if possible.

**Comment by florissmit1** [comment]
#742

**Comment by srinivas-iosdev** [comment]
Hi @zubers1128 ,
If you need to get continuous detection for GPS Service, please use the `getPositionStream()` without providing `timeLimit` parameter. Because, when the timeLimit threshold is reached then the continuous location-detecting-service will be stopped.
After that, please `listen()` to the location stream subscription. Here, we have `onData` parameter which provides you the updated location, `onError` will provide you the errors. So, in that `onError` parameter function please handle you application when location is turned off.
