### ISSUE TITLE
Not able to get the location when the app is in background.

### ISSUE THREAD

**Issue by dhruv048** [Baseflow/flutter-geolocator#595]
## 💬 Questions and Help

First of all let me provide the simple code i used.
`    Geolocator.getPositionStream().listen((event) {
      print(event.longitude);
    });
`
This works fine when the app is in foreground but it stops getting location as soon as i make the app go to background. Can anyone please help me with the issue? 

I have added the permission request code in the app manifest.xml file

```    
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
 <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
```
Is there anything else i need to change or add? 

Thanks in advance :)

**Comment by hordeariibarley** [comment]
@dhruv048 
are you closing the app? If the screen is locked or minimised, do you have the same behaviour?
I have a similar question on https://github.com/Baseflow/flutter-geolocator/issues/372#issuecomment-727656084
Similar code and it stops to listen after some seconds when screen is locked.

I am not sure if your case is a background condition, but bg is covered on this issue here https://github.com/Baseflow/flutter-geolocator/issues/53.
And for minimised or screen locked, this is apparently fixed on https://github.com/Baseflow/flutter-geolocator/issues/372 , but for me didn't work (6.1.6^)

**Comment by dhruv048** [comment]
@hordeariibarley thanks for your response,
i just found out this plugin [https://pub.dev/packages/background_location](url) 
it works fine for me, hope it does the same for you :)
