### ISSUE TITLE
Geolocator on lock screen or app minimised

### ISSUE THREAD

**Issue by hordeariibarley** [Baseflow/flutter-geolocator#597]
## 💬 Questions and Help

If the screen is locked, Geolocator should still work on 6.0.0 above? or is this background support?

I am adding the position on a list like the code below, but if the screen is locked, no position is added. I am using a Samsung to test (model SM-A107M and Android 10) with "always" GPS config. Am I losing something?
(I've already added all <uses-permission> and upgraded to compileSdkVersion 30)

```
_positionStreamSubscription = GeolocatorPlatform.instance
        .getPositionStream(desiredAccuracy: LocationAccuracy.best)
        .listen((Position position) {
      setState(() {
        _positions.add(position);
      });
}),
```

Thanks for the amazing package!

**Comment by hordeariibarley** [comment]
similar to https://github.com/Baseflow/flutter-geolocator/issues/372#issue-547277246, but it isn't working for me

**Comment by mvanbeusekom** [comment]
@hordeariibarley when you lock your device the application is moved into the background, meaning this would require the geolocator to run in the background (which is currently not supported).

On iOS you might see an additional three seconds of activity since iOS gives applications three seconds to clean up before the app is moved into the background but after this it will also stop receiving updates.

The best thing to do at the moment is to listen for application [life cycle events](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeAppLifecycleState.html) and cancel the `StreamSubscription` when the App is `paused` and resubscribe when the App `resumes`.

Hope this helps, if you have additional questions I am happy to help.

**Comment by hordeariibarley** [comment]
I needed all positions during a specific period of time, so I would need the background feature
I guess I will have to wait, I didn't want to change this plugin also, best one related to location I could find!

Thanks for the answer @mvanbeusekom!
