### ISSUE TITLE
distanceFilter wrong in second time getPositionStream 

### ISSUE THREAD

**Issue by tantv-2058** [Baseflow/flutter-geolocator#608]
## 🐛 Bug Report
I have two listener listening location changes

```dart 
Geolocator.getPositionStream(distanceFilter: 50).listen((Position position) {
      print('Listener 1: ' $position);
    });
```

```dart 
Geolocator.getPositionStream(distanceFilter: 5).listen((Position position) {
      print('Listener 2: ' $position);
    });
```
Listener 2: I get no position when moving <50 m

**Version:** 6.1.7

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @tantv-2058, 

This is correct, when you have a stream active, the `getPositionStream` will return you the same stream when calling it again (even though you specify different parameters). 

This is because Flutter only allows one stream active on the same channel name. I can solve this by adding identifiers to the channel names but that would make the geolocator a lot more complex (since we then need to keep track of channels and identifiers).

When building the geolocator plugin, I could not think of any situation where I would need to listen to multiple stream simultaneously so I decided not to add the extra complexity.

**Comment by JBBx2016** [comment]
@mvanbeusekom I disagree that listening to multiple streams simultaneously is a rare situation. Different features have different requirements to position accuracy/frequency, and many apps contain several different features.

It is of course possible to use the strictest LocationOptions for the entire app, but this drains battery.

At least the developer should be made aware of this, instead of the error failing silently.
