### ISSUE TITLE
isLocationServiceEnabled returns true even when the GPS is off

### ISSUE THREAD

**Issue by bajajsahil** [Baseflow/flutter-geolocator#631]
Hi,

Below code is returning ```true``` even when the mobile GPS is off (location is off).

```dart
await Geolocator.isLocationServiceEnabled();
```

Flutter - 1.22.4
Geolocator - 6.1.13
Device - Redmi Note 5 Pro (mobile) • 99c86a4b • android-arm64 • Android 9 (API 28)
Brand - Xiomi

It's working fine on Samsung S9 - Android 10.

**Comment by RacinesAndres** [comment]
Greetings, I have this same problem and it is because of the location mode. **isLocationServiceEnabled** only marks "**true**" when in device mode, in other modes it always marks it as "**true**" even if localization is disabled.

**Comment by tronghuy5555** [comment]
Some devices does not use google location service to get location. I see the code `isLocationServiceEnabled` use google location services to check it. So, we should use `Android Location Manager` instead of `Google Service` for check it.

**Comment by florissmit1** [comment]
I reproduced the issue on my Oppo Reno 2Z and it shows the expected behaviour.

Steps to reproduce:

- Forked the Android example
- In the main.dart, added the following code snippet to the onPress of the check permission button:
```
await Geolocator.isLocationServiceEnabled().then((enabled) => {
                  if(enabled){
                    log('Location enabled')
                  }else{
                    log('Location disabled')
                  }
```
- Requested location permission in the example application
- Turned on my location service
- Logged the status of the locationServiceEnabled method using the code snippet mentioned above
- Turned off my location service
- Logged the status of the locationServiceEnabled method

Both logs were correct according to the location settings on the phone (enabled when GPS was on, disabled when GPS was turned off)

I expect the issue to be device bound.

**Comment by bajajsahil** [comment]
@florissmit1 Yes, it is device-specific. It's working perfectly for Samsung device. I am having an issue with Xioami.

**Comment by SergioEric** [comment]
It's a problem related with MIUI layer, you can use a try catch when requesting getCurrentPosition()

```dart
try{
  final position = await Geolocator.getCurrentPosition();
  // then if there is a `position` update your UI or handle as you want
}catch(e,_){
}
```
