### ISSUE TITLE
final positionMap = await positionFuture; never returns

### ISSUE THREAD

**Issue by lukertaylor** [Baseflow/flutter-geolocator#632]
I can't find a way to get 'Geolocator.getCurrentPosition()' to complete successfully.

 I'm using the Android emulator that came with Android Studio. I've set a location.

The command I'm using is 'Position currentPosition = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.low, forceAndroidLocationManager: true);'

Geolocator.isLocationServiceEnabled() is returning true. Geolocator.checkPermission() is returning 'LocationPermission.whileInUse'.

I tried tracing through with Debug and it looks like 'final positionMap = await positionFuture' in method_channel_geolocator.dart never returns.

Any ideas?

**Comment by mvanbeusekom** [comment]
Hi @lukertaylor, 

This is very much possible, since the Android Emulator cannot emulate acquiring the location through cell-network triangulation. Which in this case is used since you specified a location accuracy value of `low`. 

You could try increasing the accuracy level to `high` or `best` which should return a location based on GPS (which is emulated when configuring the location in the emulator settings). Also make sure you have the `android.permission.ACCESS_FINE_LOCATION` in you AndroidManifest.xml file.

**Comment by lukertaylor** [comment]
Hi Maurits (@mvanbeusekom), thank you so much for replying. Your recommendation immediately solved the issue.

Best wishes,

Luke
