### ISSUE TITLE
openAppSettings() opens an inconvenient page

### ISSUE THREAD

**Issue by averstuyf** [Baseflow/flutter-geolocator#638]
## 🐛 Bug Report

Geolocator.openAppSettings() opens the app settings page. This forces users to navigate two levels down from app settings page, to the app location permission page itself.

Google provided a video with their most recent changes to the Location Permissions policy: [youtu.be/b0I1Xq_iSK4?t=94](https://youtu.be/b0I1Xq_iSK4?t=94). This shows how, instead of the app settings page, the app location permission page can be opened directly. 

### Expected behavior

Open the app location permission page instead of the app settings page.

### Reproduction steps

Call Geolocator.openAppSettings() with the app's location permission set to denied.

### Configuration

Google Pixel 2 XL, updated. Android 11, API 30. Flutter 1.22.5. Project target API 30.

**Version:** 1.1.13

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @averstuyf,

Unfortunately the page shown in the video cannot directly be called programmatically. This page is automatically shown when after you requested and was granted `ACCESS_FINE_LOCATION` permission, you request the `ACCESS_BACKGROUND_LOCATION` permission. In this case the Android system will not show the normal dialog but will redirect the user to the page shown in the video. 

The closest we can get programmatically is the App settings page where the user needs to select the "Permissions" followed by the "Location" options first before he or she is redirected the page where location permissions can be updated.

P.S. since the geolocator doesn't support acquiring location updates in the background we also don't offer an explicit option to request the background permissions.
