### ISSUE TITLE
android permission

### ISSUE THREAD

**Issue by pouria-z** [Baseflow/flutter-geolocator#640]
## 💬 Questions and Help

Hi,
Is there any way to get user's lat and lon with only ACCESS_COARSE_LOCATION permission?
I tried to get these two parameters with and without ACCESS_FINE_LOCATION. But it **just** worked **with**  this permission.

**Comment by mvanbeusekom** [comment]
@pouria-z yes it is possible but there are a few constraints. We have the following documented on our README.md page (part of the Android section):

>NOTE: Specifying the ACCESS_COARSE_LOCATION permission results in location updates with an accuracy approximately equivalent to a city block. It might take a long time (minutes) before you will get your first locations fix as ACCESS_COARSE_LOCATION will only use the network services to calculate the position of the device. More information can be found [here](https://developer.android.com/training/location/retrieve-current#permissions).

To add to this, make sure you always test on a real device since the emulator doesn't emulate network / cell services and cannot determine the location that way.
