### ISSUE TITLE
getCurrentPosition on emulator never returns

### ISSUE THREAD

**Issue by ryanlangton** [Baseflow/flutter-geolocator#641]
## 🐛 Bug Report

Calling the method, getCurrentPosition never returns data, it goes past this line of code and never hits the next line. This is wrapped in a try/catch and an exception is never thrown either. Running on Android emulator. Pixel API 28

I've tried this on emulators targeting v28 and v29 android. The behavior is the same. I do get a popup asking if I want to allow the application to access the devices location which I confirm. I have also "set location" in the extended controls for the emulator.

### Expected behavior

Return a location (lat/long)

### Reproduction steps

Add this line of code, use an android emulator.
final position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best, forceAndroidLocationManager: true);

### Configuration

geolocator: ^6.1.13

**Platform:** 
- [ ] :iphone: iOS
- [X] :robot: Android

**Comment by mvanbeusekom** [comment]
@ryanlangton which permissions have you listed in your AndroidManifest.xml file? 

This can happen when using the `android.permission.ACCESS_COARSE_LOCATION`. This permission only permits the app to determine the location based on the network cell towers. Since the emulator doesn't have an active/ real cell connection it cannot simulate the coordinates and therefore never returns. This is a well known issue with testing location services on an Android emulator. 

In general the advise would be to use the `android.permission.ACCESS_FINE_LOCATION` permission which permits the App to access the location through GPS and can also be emulated by the Android emulator. 

If you really have to use the `android.permission.ACCESS_COARSE_LOCATION` permission you will have to test on a real Android device. Note that the first time it could take up to several minutes before the Android device is able to acquire a proper fix.

More information can also be found in the "Usage" chapter of our [README.md](https://pub.dev/packages/geolocator#usage) specifically in the Android section.

Please let me know if this helps?

**Comment by ryanlangton** [comment]
Changing from `android.permission.ACCESS_COARSE_LOCATION` to `android.permission.ACCESS_FINE_LOCATION` in the AndroidManifest.xml fixed the problem. Thank you.

**Comment by MrWaggel** [comment]
With Android emulator I occur this bug this mostly on newly created AVDs, what works for me is opening the google maps app in the emulator and click through the popups. (recently tested on 5.0 with Google APIs)

**Comment by paulthewall502** [comment]
I am using a physical Android device for my testing, and still get the same error  @ryanlangton had.
How can I fix this?

**Comment by aliakhtar** [comment]
Please consider adding this issue to the documentation, I just encountered this as well and had no idea how to solve it until I found this issue.

**Comment by xlfdyzcs** [comment]
> I am using a physical Android device for my testing, and still get the same error @ryanlangton had.
> How can I fix this?

same issu，When I use an Android 10 OnePlus phone, it doesn't return any data

**Comment by BiscoMan** [comment]
> With Android emulator I occur this bug this mostly on newly created AVDs, what works for me is opening the google maps app in the emulator and click through the popups. (recently tested on 5.0 with Google APIs)

I know this issue is closed, but for future people that reads this topic, this worked for me. 
I have `android.permission.ACCESS_FINE_LOCATION` and `android.permission.ACCESS_BACKGROUND_LOCATION` in my AndroidManifest.xml. I am asking the user's permission to access location when the app starts for the first time, with `permission_handler` package, and even though I allowed it, the code was stuck in getting the location. Opened Google maps, centered my emulator location with Google Maps center location button, and it unlocked the my app 😅 .
The same code works fine in my Xiaomi Mi 10 Lite, so I suppose it is some emulator issue 🤷 .
Thanks @MrWaggel
