### ISSUE TITLE
timeLimit is throwing errors

### ISSUE THREAD

**Issue by lukepighetti** [Baseflow/flutter-geolocator#650]
I have a `timeLimit` set for 1 minute, and I get this error when the device is sitting.

```
Unhandled Exception: TimeoutException after 0:01:00.000000: Time limit reached while waiting for position update.
```

I don't expect there to be any errors at all. I just expect it to update the position even if we haven't moved `distanceFilter` meters.

**Comment by mvanbeusekom** [comment]
That is indeed expected behavior. The `timeLimit` parameter is meant as a timeout to cancel the method in case where retrieving the location takes to long. 

As per the documentation:

> Throws a TimeoutException when no location is received within the supplied timeLimit duration.

More details: https://pub.dev/documentation/geolocator/latest/geolocator/Geolocator

**Comment by lukepighetti** [comment]
Is there an explanation of the real world use-case for this timeout?

The use-case I was expecting to solve with it was this:

You set a distance update resolution in meters.
You set a minimum update interval as a Duration.
You set a maximum update interval as a Duration.

If the update resolution is 10 meters and the maximum is 1 minute, if you only move 5 meters it will trigger a new location after 1 minute.

Currently it just kills the stream.

**Comment by mvanbeusekom** [comment]
The most common use case is that in some situations it might take a long time to acquire a position (this can have multiple reasons). In this case some developers would like to register a timeout which will cancel the request and give them feedback so they can inform their users. This has been a requested feature before version 6.0.0 (where I first introduced the timeout). See also issue #242.

I am not sure the workflow you describe will work, since the native API's don't support this configuration. They only provide an API to specify a distance and minimum update interval. Hence they will not return any location updates if the configured conditions are not met, so I won't be able to send something back. Theoretically I could build something that would query the current position when the maximum update interval is reached but in that case I am also not sure how long it will take to acquire that position (this might still take several seconds or more depending on GPS connection, desired accuracy, configured permissions, network reception, etc..). Meaning this will not be very reliable, and I would imagine it would be better if you do this locally in your App (e.g. keep a manual timer and request the current position when you haven't received any feedback from the stream yet, that way the stream stays open and you have full control on the request for the current position).

If you have any other solutions or ideas I am very open to them.

**Comment by lukepighetti** [comment]
We can keep this closed. Thanks for the thoughtful reply.
