### ISSUE TITLE
Usage with Flutter 1.26 and Android SDK 29

### ISSUE THREAD

**Issue by Pitazzo** [Baseflow/flutter-geolocator#652]
Hey guys,
thanks for developing this useful plugin. We would like to know if would be possible to use this plugin with Flutter version `1.26.0-13.0.pre.122` and compiled SDK 29, and if so, which version of the plugin to target.

We don't need any other feature than getting location updates but for us being able to target SDK 29 (Android 10) is a requirement.

**Comment by mvanbeusekom** [comment]
Hi @Pitazzo,

Android 10 is fully supported since version 6.0.0 of the geolocator plugin. Every version of the geolocator plugin is tested against stable version of Flutter. 

We also have a null-safe version of the geolocator plugin which is kept up to date with the current stable version. The most current null-safe version is 7.0.0-nullsafety.5 (which is the null safe equivalent of version 6.1.14).

**Comment by Pitazzo** [comment]
So, just to check if I got it clear, can we safely use version 6.0.0 of the plugin while targeting SDK 29?

**Comment by mvanbeusekom** [comment]
If you'd ask me I would use the latest stable version which is 6.1.14 (or if you are going full on null-safety you should go with 7.0.0-nullsafety.5).
