### ISSUE TITLE
Location permission request pop up not coming in android VERSION 11(SDK - 30)

### ISSUE THREAD

**Issue by chirag-chopra** [Baseflow/flutter-geolocator#653]
### Expected behavior
It should show pop-up for location permission. This plugin is working perfectly on below SDK 30.

### Configuration

**Version:** 1.22.6
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (6 days ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by IonVillarreal** [comment]
could you solve the problem?

**Comment by chirag-chopra** [comment]
> could you solve the problem?

No..... and u?

**Comment by kustraslawomir** [comment]
Same issue with geolocator: 6.1.13.

**Comment by kustraslawomir** [comment]
LocationPermission permission = await Geolocator.checkPermission();

LocationPermission.denied.

**Comment by kustraslawomir** [comment]
As described in the guide on how to request location access at runtime, you should perform incremental location requests. If your app targets Android 11 or higher, the system enforces this best practice. If you request a foreground location permission and the background location permission at the same time, the system ignores the request and doesn't grant your app either permission.

https://developer.android.com/about/versions/11/privacy/location

**Comment by kustraslawomir** [comment]
@chirag-chopra  @IonVillarreal 
So to fix this, you guys have to remove one of these:

Future<void> _requestLocationPermissions(BuildContext context) async {
    Map<Permission, PermissionStatus> statuses = await [
      Permission.location,
      **Permission.locationAlways,
      Permission.locationWhenInUse,**
    ].request();
    
    Just remove locationAlways or locationWhenInUse.

**Comment by chirag-chopra** [comment]
> locationWhenInUse

```
Future<Position> getCurPosition() async {
    Position position;
    LocationPermission permission = await Geolocator.checkPermission();
    if (permission != LocationPermission.denied ||
        permission != LocationPermission.deniedForever) {
      position = await Geolocator.getCurrentPosition(
          desiredAccuracy: LocationAccuracy.best);
      return position;
    }
    return null;
  }
```


I am using Geolocator like this... What changes needs to be done in order to make it work on SDK 30?

**Comment by mvanbeusekom** [comment]
@chirag-chopra did you by any chance denied the permissions twice? Could you check if the `await Geolocator.checkPermission()` call returns `deniedForever`?

I can only reproduce this scenario with the following steps (but in this case it is perfectly correct that the pop-up is not shown anymore):

1. Launch the application (for the first time);
2. Request permissions and select `deny`;
3. Request permissions again, and again select `deny` (now Android 30 will automatically assume that the user doesn't want to be requested again, so we assign status `deniedForever`);
4. If we try to request permissions a third time, no pop-up is shown (this is blocked by Android 30 since it assumes the user doesn't want to be bothered anymore);

The official Android documentation can be found here: https://developer.android.com/about/versions/11/privacy/permissions#dialog-visibility
