### ISSUE TITLE
getLocation Not working in China

### ISSUE THREAD

**Issue by TyroneZeka** [Baseflow/flutter-geolocator#656]
## 💬 Questions and Help

For questions or help we recommend checking:
I recently started suing Flutter but I am in China and it seems like I cannot get the location could it be because of the Firewall or I am missing something. I followed along everything on the page and I get an error Waiting for a blocking GC ProfileSaver

- The [Flutter tag in Stack Overflow](https://stackoverflow.com/questions/tagged/flutter)

**Comment by mvanbeusekom** [comment]
Hi @TyroneZeka, 

First a quick question, in the title of this issue you mention the `getLocation` method. This is not a method defined by the geolocator plugin. Is this a typo or are you confusing plugins?

If you are using the geolocator it could indeed be the case that the goverment firewalls are blocking the position from being returned on Android devices. This is because the geolocator defaults to using the `FusedLocationProviderClient` SDK to acquire position information. This SDK communicates with the Google Play Services in the background which is something that is blocked in China. To resolve this issue the geolocator can be forced to fallback on the `LocationManager` SDK which doesn't rely on the Google Play Services and should work fine in China (or other countries blocking the use of Google Play Services). To do so you can set the `forceAndroidLocationManager` parameter of the `getCurrentPosition` or `getPositionStream` methods to `true`. For example:

```dart
final position = await Geolocator.getCurrentPosition(forceAndroidLocationManager: true);
```

Hope this helps.

**Comment by TyroneZeka** [comment]
> Hi @TyroneZeka,
> 
> First a quick question, in the title of this issue you mention the `getLocation` method. This is not a method defined by the geolocator plugin. Is this a typo or are you confusing plugins?
> 
> If you are using the geolocator it could indeed be the case that the goverment firewalls are blocking the position from being returned on Android devices. This is because the geolocator defaults to using the `FusedLocationProviderClient` SDK to acquire position information. This SDK communicates with the Google Play Services in the background which is something that is blocked in China. To resolve this issue the geolocator can be forced to fallback on the `LocationManager` SDK which doesn't rely on the Google Play Services and should work fine in China (or other countries blocking the use of Google Play Services). To do so you can set the `forceAndroidLocationManager` parameter of the `getCurrentPosition` or `getPositionStream` methods to `true`. For example:
> 
> ```dart
> final position = await Geolocator.getCurrentPosition(forceAndroidLocationManager: true);
> ```
> 
> Hope this helps.

Thanks a lot, I will try this and yes I meant the getCurrentPosition from the geolocator plugin, I tried to use forceAndroidLocationManager parameter on call but still not working and I tried again to update on the geolocator.dart. I am thinking of installing a vpn in my emulator.
