### ISSUE TITLE
distanceBetween method is not returning exact or even right values 

### ISSUE THREAD

**Issue by uzairleo** [Baseflow/flutter-geolocator#666]
### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
Distance between uses the Haversine formula to calculate the distance between two points. This is clear mentioned in the API documentation of the method (see [here](https://pub.dev/documentation/geolocator/latest/geolocator/Geolocator/distanceBetween.html) and also shows up in your IDE). This means it is the most direct distance between the two points. 

Since you are not really leaving any other information to explain you problem I will assume this is an user error and close this issue.

**Comment by tjmeal** [comment]
Hello i thought i was facing the same issue but please correct if am wrong, i believe it calculates correctly the distance just the format is wierd.

Using version 6.2.1

a) calculates it in kilometers right ?
b) When we get result of 14415.150269902417 > when i using the same coordinates to get that result > if i use an online tool give me 14 > so i guess the resulted number 14415.150269902417 > 14.416..... is that correct ? 

Thanks a lot for your time and work.

**Comment by mvanbeusekom** [comment]
Hi @tjmeal, 

The `distanceBetween` returns a value in meters (which is documented in the API [here](https://pub.dev/documentation/geolocator_platform_interface/latest/geolocator_platform_interface/GeolocatorPlatform/distanceBetween.html). 

Meaning if you want to calculate the distance in kilometers you should divide the result by 1000. In your case this should result in a value of `14.415150269902417` (meaning 14 kilometers, 415 meter, 15 centimeter, etc...). The format is indeed a bit strange but we decided to supply the raw data back to the developers and not make any decisions for you since it would be trivial to do calculations yourself.

Hope this helps.

**Comment by tjmeal** [comment]
Yeah thats what i did, i just right it here because that was also my first impression that it didnt work correctly, but it does except in a format that we don't except :)
