### ISSUE TITLE
Depedency on geolocator_platform_interface and more!

### ISSUE THREAD

**Issue by danielgchap** [Baseflow/flutter-geolocator#686]
## 🐛 Bug Report

Upgrading to geolocator: 7 and upgrading geocoding: 2.0.0.
I get this:

`Running "flutter pub get" in PrayerPal...                       
Because geolocator >=7.0.0 depends on geolocator_platform_interface ^2.0.0 which depends on plugin_platform_interface ^2.0.0, geolocator >=7.0.0 requires plugin_platform_interface ^2.0.0.`

Why is there all these dependencies now?
When I add the geolocator_platform_interface, it then wants plugin_platform_interface on so on.

Thoughts?

Thanks!

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@danielgchap I cannot reproduce the problem you describe. I have created a brand new application using `flutter create geo_test` and added `geolocator: ^7.0.0` and `geocoding: ^2.0.0` as dependencies which works just fine. Steps I took:

1. Create new application: `flutter create geo_test`;
2. Change into new folder: `cd geo_test`;
3. Added dependencies to the pubspec.yaml;
4. Download the dependencies from pub.dev: `flutter pub get`;
5. Run the application: `flutter run`.

This simply showed the default counter app which worked fine. You don't need to add a separate dependency to the `geolocator_platform_interface`. The `geolocator` package will download this by itself as a sub-dependency. The `geolocator_platform_interface` is simply an interface package  which makes the geolocator work cross-platform (this is part of the federated architecture which is documented [here](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins)).

It is possible that you are using another plugin that conflicts with the geolocator and geocoding plugins. Most plugins have been migrated to null safety now and require a dependency on version 2.0.0 of the `plugin_platform_interface`, plugins that haven't been upgraded probably still depend on version 1.0.x of the `plugin_platform_interface` causing the dependency conflict. A few thing you could try (in order, and only go to the next step if the previous didn't work):

1. Run `flutter clean` and then `flutter pub get`;
2. If that didn't work try running `flutter pub upgrade` to update all packages to the latest compatible version;
3. If that didn't work try running `flutter pub outdated` this should show you a list of packages that have newer version but can't be updated automatically (due to breaking changes). Try updating all these packages manually;

If you need more help please provide some additional information:
- The output of the `flutter doctor -v` command;
- An overview of the dependencies in your project (if you don't want of can't share the contents of the `pubspec.yaml`, please list the contents of the `dependencies`, `dev_dependencies` and if available `dependency_overrides` sections).

**Comment by danielgchap** [comment]
Hi @mvanbeusekom thank you so much for taking the time to respond and so quickly! I have a large amount of pubs in my project and yes, I went down the string of dependencies and had to update a lot and especially since Firebase released a bunch of updates and Flutter 2 is out on Stable. 

Anyhow, all that to say, it's not THIS package in error

Sorry! Thank you!

**Comment by zumrywahid** [comment]
You can reproduce the error when you add following packages,

```
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  geolocator: ^7.0.1
```

I have added these packages in a new project and i am still getting error.
