### ISSUE TITLE
iOS: Location access denied even usage description is provided

### ISSUE THREAD

**Issue by haashem** [Baseflow/flutter-geolocator#699]
## 🐛 Bug Report

I have added only this line to info.plist instead of adding separate when in use and always usage descriptions :
`Privacy - Location Always and When In Use Usage Description`

but when I try to get current location, it emits location access denied!

### Expected behavior
It should enable access to location service
### Reproduction steps

only add this usage description to info.plist file
`NSLocationAlwaysAndWhenInUseUsageDescription`

then try to get current location

### Configuration

**Version:** 7.0.1

**Platform:** 
 :iphone: iOS

**Comment by mvanbeusekom** [comment]
@haashem the Geolocator doesn't really check/ validate the `NSLocationAlwaysAndWhenInUseUsageDescription` key since it is purely meant to request permissions to access location in the background (unlike the name makes you believe). This is clearly documented in the Apple documentation [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysandwheninuseusagedescription?language=objc).

Since the Geolocator doesn't support running in the background this key was never added. However since the deprecated `NSLocationAlwaysUsageDescription` key was supported (pre-iOS 11) I will add this key also to the code base. However you will still have to specify the `NSLocationWhenInUseUsageDescription` key in your `Info.plist` file or you will face the following exception (which again explains you'll need to add both keys):

```
This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain both “NSLocationAlwaysAndWhenInUseUsageDescription” and “NSLocationWhenInUseUsageDescription” keys with string values explaining to the user how the app uses this data
```
