### ISSUE TITLE
Request Always Permission on iOS

### ISSUE THREAD

**Issue by srombs** [Baseflow/flutter-geolocator#735]
## 💬 Questions and Help

Hello,
How do I request the "Always" permission on iOS. I have used `Geolocator.requestPermission()` but it only grants `LocationPermission.whileInUse`, I am hoping to get the always permission prompt which gives me back `LocationPermission.always`

Thank you.

For questions or help we recommend checking:

- The [Flutter tag in Stack Overflow](https://stackoverflow.com/questions/tagged/flutter)

**Comment by delivastza** [comment]
Hi,

This package checks for **NSLocationWhenInUseUsageDescription**, if it is there it will request **whileInUse** permission, regardless of any other location key you provide in info.plist, such as if you want **always** location with **NSLocationAlwaysAndWhenInUseUsageDescription**. See image below. 
![image](https://user-images.githubusercontent.com/63346257/118983654-f3a9b200-b97c-11eb-800e-8f12ed7c56e8.png)
I forked the project, switched the if logic so that always permisson gets called if it is found first and it works. 

One suggestion is that you check the permission status in app and have a UI in app to show the current permission status and text on why you need always access. On this same UI there should be an action button, which when clicked will take the user to the location settings `geolocator. openLocationSettings()` to allow the user to set the **always** location option. 

**NB!** Not sure which version of iOS you are testing on, but for iOS 13 and above, the first location permission dialog will never show an "Always" option even when requesting for always permission. Here is an [article to explain this](https://hypertrack.com/blog/2020/06/24/impact-of-ios13-ios14-location-permissions-on-background-location-access/). iOS 14 also introduced an authorization accuracy feature which I am sure this package will support soon.

**Comment by florissmit1** [comment]
I think the best solution is to add the right properties to the Info.plist like @delivastza is mentioning. Is your question answered?
