### ISSUE TITLE
No google services compile option

### ISSUE THREAD

**Issue by selankon** [Baseflow/flutter-geolocator#841]
## 🚀 Feature Requests

I would like that at compile time, the plugin use pure Android location manager

### Contextualize the feature

To use this plugin on flutter apps that have to be published on Fdroid, I need to have an apk without any google location classes. 

### Describe the feature

I'm trying to find the way to do this, with the same code, just adding maybe a flutter build option, or something on gradle, to specify if Android location manager or both have to be added to the APK. 

I'm not sure if this is possible to be done, and how difficult can be. For the moment i have two versions, one including this plugin, and the other without. Witch is annoying. 

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by maxammann** [comment]
We are also in need of such a feature

github.com/digitalfabrik/ehrenamtskarte


There is also a floss fork which is more or less uptodate: https://gitlab.com/hanntech-gmbh/free2pass/flutter-geolocator-floss

**Comment by mvanbeusekom** [comment]
This issue should be solved with the release of `geolocator_android` version 3.1.8.

**Comment by Robbendebiene** [comment]
@mvanbeusekom It seems like excluding the dependency is sadly not enough. The full discussion can be found here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10991 In short the argument is: even if we exclude GMS via gradle it will still be used on compile time and just be excluded as a runtime dependency.

Since you already separated GMS and the android location manager very well in your code, I thought it might be possible to create two android packages: `geolocator_android_floss` and `geolocator_android`. Most of the core android geolocator code would be located in `geolocator_android_floss` while `geolocator_android` imports `geolocator_android_floss` and implements the 2 files that use GMS on top. So this should ensure compatibility. To exclude GMS compelty as an app developer we then could use an override dependency (in the pubspec) of  `geolocator_android` with `geolocator_android_floss`.
I feel like this could work, but I'm not sure. @mvanbeusekom What do you think about it? Any other ideas? I also read about: https://docs.gradle.org/current/userguide/feature_variants.html but I don't have enough knowledge about this stuff.

@maxammann Would you be interested on working on this together if we have a proposed solution that @mvanbeusekom is happy with?

To get a better idea of how I imagine the file structure I've described above I started moving and patching some files here:
https://github.com/Robbendebiene/flutter-geolocator

**Comment by maxammann** [comment]
> Since you already separated GMS and the android location manager very well in your code, I thought it might be possible to create two android packages: geolocator_android_floss and geolocator_android. Most of the core android geolocator code would be located in geolocator_android_floss while geolocator_android imports geolocator_android_floss and implements the 2 files that use GMS on top. So this should ensure compatibility. To exclude GMS compelty as an app developer we then could use an override dependency (in the pubspec) of geolocator_android with geolocator_android_floss.
I feel like this could work, but I'm not sure. @mvanbeusekom What do you think about it? Any other ideas? I also read about: https://docs.gradle.org/current/userguide/feature_variants.html but I don't have enough knowledge about this stuff.

That would be the clean approach. I think this should work, but would require some massive refactoring. An alternative approach which I already mentioned in some discussion would be to create FOSS GMS shims. It might even be possible to simply use `https://github.com/microg/GmsCore/tree/master/play-services-location` during building and make the build-process google free.

> @maxammann Would you be interested on working on this together if we have a proposed solution that @mvanbeusekom is happy with?

I'm a bit back-and-forth whether I would like to work on this. I don't really agree that the way F-Droid is handling some of this is in the interest of "the greater good". I can understand their ethical standpoint, but this whole discussion went a little bit too far.

---

Opinion: I think this whole problem/discussion with F-Droid, does not promote FLOSS for users, but prohibits it. In order to solve this issue cleanly, we would need to refactor flutter-geolocator (Which I sadly think won't happen, because there is no benefit for 99% of the developers and 100% for users).

**Comment by Robbendebiene** [comment]
I think the re-factoring might seem big due to the amount of files that will be moved around, but since actually only 2 files in total include the GMS dependency it **could** be fairly simple. But @mvanbeusekom has to decide if he can accept this fragmentation for the (admittedly) small benefit.

> It might even be possible to simply use https://github.com/microg/GmsCore/tree/master/play-services-location during building and make the build-process google free.

Yeah, this solution actually might provide some benefits. I might try this. Please let me know if you manage to get it running with microG.

> I'm a bit back-and-forth whether I would like to work on this. I don't really agree that the way F-Droid is handling some of this is in the interest of "the greater good". I can understand their ethical standpoint, but this whole discussion went a little bit too far.

I have a similar feeling. I'm still unsure if they even have a valid point from a technical point of view.

**Comment by Robbendebiene** [comment]
I'm not sure if this is a viable option, but a very simple solution would be if geolocator could read from an environment variable or a project property that decides whether it should include the google dependency or the microg dependency.
So [this line](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_android/android/build.gradle#L45) would contain a conditional check like:

```gradle
dependencies {
    if (CONDITON) {
        def microg_version = "0.2.24.214816"
        implementation "org.microg.gms:play-services-location:$microg_version"
    } else {
        implementation 'com.google.android.gms:play-services-location:17.0.0'
    }
    implementation 'androidx.core:core:1.2.0'
}

```
This wouldn't require any further code changes, and it would even allow using the Fusedlocationprovider on devices that have microg installed instead of gms.

**Comment by maxammann** [comment]
> I'm not sure if this is a viable option, but a very simple solution would be if geolocator could read from an environment variable or a project property that decides whether it should include the google dependency or the microg dependency.
> So [this line](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_android/android/build.gradle#L45) would contain a conditional check like:

Looks good if it works! :tada:

**Comment by mvanbeusekom** [comment]
Hi @Robbendebiene, 

The problem is that I am not at all familiar with FLOSS or F-Droid and that makes it hard for me to follow, test and ensure quality is up to par. This means I am indeed reluctant to go forward with any significant refactoring. 

In you last comment you mentioned using an environment variable to swap out dependencies. This part looks straight forward and if it works I have nothing against it if:

1. By default the Google Play Services are used;
2. This is properly documented.

**Comment by maxammann** [comment]
> Hi @Robbendebiene,
> 
> The problem is that I am not at all familiar with FLOSS or F-Droid and that makes it hard for me to follow, test and ensure quality is up to par. This means I am indeed reluctant to go forward with any significant refactoring.
> 
> In you last comment you mentioned using an environment variable to swap out dependencies. This part looks straight forward and if it works I have nothing against it if:
> 
>     1. By default the Google Play Services are used;
> 
>     2. This is properly documented.

I think those changes can also be done in downstream applications. So there is no strict requirement that we adjust Gradle files of flutter-geolocator.

**Comment by Robbendebiene** [comment]
@mvanbeusekom Thanks for your answer. I'm also in favor of providing an option to replace gms with microg. The problem is that `org.microg.gms:play-services-location` is not published on [maven](https://search.maven.org/search?q=g:org.microg.gms) even though an implementation exists (see [here](https://github.com/microg/GmsCore) and [here](https://github.com/microg/GmsCore/wiki/Implementation-Status)) wherefore we cannot simply include it like that.

@maxammann If we do it downstream I'm pretty sure we run into the same problem as we already did with just excluding GMS downstream. They will argue that one dependency still depends on something proprietary..

**Comment by maxammann** [comment]
> @mvanbeusekom Thanks for your answer. I'm also in favor of providing an option to replace gms with microg. The problem is that `org.microg.gms:play-services-location` is not published on [maven](https://search.maven.org/search?q=g:org.microg.gms) even though an implementation exists (see [here](https://github.com/microg/GmsCore) and [here](https://github.com/microg/GmsCore/wiki/Implementation-Status)) wherefore we cannot simply include it like that.
> 
> @maxammann If we do it downstream I'm pretty sure we run into the same problem as we already did with just excluding GMS downstream. They will argue that one dependency still depends on something proprietary..

You are probably right :D we could publish our own maven repo. Maybe my company woulf be willing to host it
