### ISSUE TITLE
getServiceStatusStream has not been implemented. 

### ISSUE THREAD

**Issue by Puspharaj** [Baseflow/flutter-geolocator#846]
## 🐛 Bug Report

Flutter 2.5 web 
  geolocator: ^7.6.2

When I try to listen for the status of the permission in the web, it throws the error. 

`getServiceStatusStream has not been implemented. `

Guess it's not implemented, but no word.

**Comment by mvanbeusekom** [comment]
@Puspharaj you are correct. The concept of a separate location service doesn't exist on the web platform. Therefore it is not possible to listen to status changes on the web. Hence the method not being implemented and throwing the exception. 

I will make sure to update the API documentation so that is reflects this information correctly.
