### ISSUE TITLE
Compass feature request

### ISSUE THREAD

**Issue by fawadkhanucp** [Baseflow/flutter-geolocator#86]
## 🚀 Feature Requests

A function that gives us the direction we need to head to get from one place to another.  An example being if I enter in coordinates/address for the Louvre museum and I'm standing at the Eiffel Tower, it will give me 266 degrees bearing. So the function itself will just return a double containing the bearing.

### Contextualize the feature

I think it could be included in the calculating distance function as it can give the distance and the direction which can be used in navigation in a straight line. 

Here is a picture of a website that shows the general idea of what I'm looking for.
![Compass](https://user-images.githubusercontent.com/35521121/44843830-b21fc880-ac62-11e8-9a6f-5c5fccc71c2b.PNG)

### Platforms affected (mark all that apply)
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by audkar** [comment]
IMHO for such functionalities like distance, direction and all other coordinates calculations/manipulations should exist separate library. geolocator lib should focus on getting coordinates from GPS. 
Separating these two functionalities would let to use calculation library without bringing GPS dependencies.

**Comment by mvanbeusekom** [comment]
@audkar personally I can also appreciate the fact that these calculations are part of the `Geolocator` library. Changes are that most of the time I will need both packages anyway, so to me it sounds useful to have them in one library.

We could however simply create a second package library and make and have the `Geolocator` simply depend on this library to perform the calculations. In that case we have best of both worlds (similar to what we now to with the `permission_handler`). This does mean that we have to maintain the same API two times (once in the Geolocator and once in the calculation library) however, since they are proven calculations I don't see that the signatures will changes.

Any thoughts on this are welcome.

**Comment by giorgio79** [comment]
https://github.com/Baseflow/flutter-geolocator/pull/310
