### ISSUE TITLE
Getting current latitude and longitude taking time in iOS devices

### ISSUE THREAD

**Issue by mohammednabil95** [Baseflow/flutter-geolocator#893]
I am using this plugin for more than 2 months, but having a problem is whenever I call this for to get current location latitude and longitude it take almost 10 seconds to get latitude and longitude only in iOS physical and simulator devices. The problem is not happening in Android physical and emulator devices.

**Comment by mvanbeusekom** [comment]
Hi @mohammednabil95 ,

This is expected behaviour and explained in more detail in issue #887. Older versions (pre-7.6.0) of the geolocator actually contained a bug when fetching the current position (see issue #629) which was fixed in [version 7.6.0](https://pub.dev/packages/geolocator/changelog#760).
