### ISSUE TITLE
MissingPlugIn Exception on Raspberry Pi

### ISSUE THREAD

**Issue by raspberrypi9** [Baseflow/flutter-geolocator#938]
Hi,

I wrote a flutter app with geolocation that works great on a Chrome(Web) target, but when I try to run it on my Raspberry Pi using flutter-pi, the rest of the app works, but the geolocation plugin throws an MissingPlugIn exception.  I'd be very grateful for any information on how to fix this.

Thanks so much for your help.

**Comment by mvanbeusekom** [comment]
Hi @raspberrypi9, 

The Raspberry Pi platform is not supported by the geolocator plugin. At the moment the geolocator supports the Android, iOS, macOS and Web platforms. A Windows implementation is worked but still in early stage of development. 

Since flutter-pi (or Raspberry Pi) is not yet an officially supported platform by Google / Flutter it self we don't have any intentions to add support any time soon. However it is possible to add an implementation yourself as mentioned also in the (flutter-pi README.md)[https://github.com/ardera/flutter-pi/blob/821a5c6a222e5ac05471ee7610b64e745e63bc4d/README.md]:

>You can now theoretically run every flutter app you want using flutter-pi, including apps using packages & plugins, just that you'd have to build the platform side of the plugins you'd like to use yourself.

Most likely the Raspberry Pi would be a standard Linux implementation. The problem however is that there are several different libraries available for Linux to determine position information and the trick is to pick (and include) the correct library in the native implementation package. Unfortunately I am not an expert on the Linux ecosystem so I am not really able to help you further on this topic. However feel free to investigate and experiment and of course I would welcome any contributions from you or the community to make Linux / Raspberry Pi support possible.
