### ISSUE TITLE
Is it possible to have multiple streams with different location settings?

### ISSUE THREAD

**Issue by comatory** [Baseflow/flutter-geolocator#939]
I wonder if it's possible to have multiple streams created from `Geolocator.getPositionStream` where each of the streams would have different `LocationSettings` argument.

I struggle with understanding how I can change the stream behaviour after it has been initialized once. The documentation states that I can cancel listening on the stream and app will stop receiving updates.

My problem is I have a part of application that creates its own stream to listen to some changes, then I have a 3rd party library that makes its call to `Geolocator.getPositionStream` with its own settings. I found out it's not possible to change my application stream afterwards. I assume this is because `Geolocator.getPositionStream` returns cached stream by whoever made the first call to it?

Can this patttern be even achieved?

**Comment by florissmit1** [comment]
Hey @comatory, when you initialise a `PositionStream`, listen to it and eventually cancel listening to the stream, the stream instance is still there in the background. Thus you can start listening to a cancelled stream again, but you can't change the `LocationSettings` in the meantime.

I think you can achieve the mentioned pattern by canceling the `PositionStream` and then nullify it, but I'm not sure since I have a hard time understanding what you mean. Can you be a bit more specific describing your problem? (You can always support your issue by posting a code snippet f.e.)

**Comment by comatory** [comment]
On Wed Jan 12, 2022 at 11:48 AM CET, florissmit1 wrote:
> Hey @comatory, when you initialise a `PositionStream`, listen to it and
> eventually cancel listening to the stream, the stream instance is still
> there in the background. Thus you can start listening to a cancelled
> stream again, but you can't change the `LocationSettings` in the
> meantime.

Yeah I figured that out after some experimenting. I will try to add
some example Flutter code if needed but it won't be small since there are some
dependencies.

In my specific scenario I use `flutter_map` plugin with 
`flutter_map_location_marker`¹ plugin.
Apart from this my application also uses `geolocator` as a direct
dependency. At certain point in my app, I create a stream with
`Geolocator.getPositionStream` to update some UI with current
latitude and longitude information.

When I do that I can stop listening to that stream with the method you
mentioned. I can then re-create new stream with different `LocationSettings`
and changes take effect like I would expect.

However during the runtime of the application I also initialize `flutter_map`
with `flutter_map_location_marker` plugin. This plugin uses `geolocator`
dependency and is creating its own stream subscription via 
`Geolocator.getPositionStream`. So even if in my application code I
cancel the stream subscription, any further calls to `getPositionStream`
with different `LocationSettings` won't take effect since the plugin
is still listening to the original stream.

I know that the focus of this library is just to facilitate updates
to device location to any consumers and its up to the user of the lib
to implement it correctly.

However I'm not sure if people developing libraries with geolocator as their
dependency realize the mechanics behind `Geolocator.getPositionStream` as
they basically "steal" the ability to control it in case one uses
also geolocator in their own code.

From your answer it seems like there is no easy solution, other than
making changes to the plugin code. It's not a straightforward thing
to do it however as it requires me to somehow manually cancel
the internal stream subscription of the plugin and **only after** that
happens, I can re-create the subscription and also provide the updated
stream to the plugin.

Maybe I'm just expecting too much functionality out of this. In ideal
world, `Geolocator.getPositionStream` would return new instance of
a stream, that way different consumers don't have to worry about
changing the configuration of their stream².

Maybe some kind of "cancel token" that could be passed to geolocator
would be a solution? That way you could do `token.cancel()` or
`token.cancel().reinitialize()` and perhaps some kind of event could
be triggered that would allow consumers of that stream to react to it
(dispose the old subscription, create a new one).

Any way, that's just an idea, not sure what the possibilies are.

¹ It's a plugin that tracks and displays a marker representing device
  location on a map created by `flutter_map`.
² I don't do native platform development so I'm not sure if it's
  possible to obtain different streams of device location with different
  configuration.

**Comment by mvanbeusekom** [comment]
@comatory unfortunately the problem here is with the native implementation on the platforms (specifically on iOS and macOS) which will cancel any existing location stream when you open another. Meaning it is impossible to listen to multiple location streams (within the sandbox of the App) at the same time. 

To keep the Geolocator plugin easy to use and predictable across all platforms we choose to keep this limitation on the other platforms (Android and Web) as well.

Although we are flattered that the `flutter_map_location_marker` uses the `geolocator` plugin as a dependency, it does indeed bring additional problems (as you mentioned it will steel the stream on iOS and macOS platforms). It would be better to update this plugin and allow developers to supply a location or stream with locations into the plugin. This way developers have full control on the location information and allows them to reuse the stream for their own purposes as well.

I will close this issue as I feel this should answer your question. If you have any further questions or feedback please feel free to leave another comment.
