### ISSUE TITLE
geolocator_android: ^3.0.2 on geolocator-8.1.0

### ISSUE THREAD

**Issue by penhorwood** [Baseflow/flutter-geolocator#967]
The pubspec on geolocator-8.1.0 is still set to use:
geolocator_android: ^3.0.2  but version 3.0.3 is out.

**Comment by florissmit1** [comment]
Hey @penhorwood, thanks for reporting your issue. The caret sign (ˆ) is used for dependencies in Flutter/Dart to indicate a range of version numbers that are allowed. The caret sign basically specifies, that all next versions can be automatically used, as long as it's a non-breaking version. So since version 3.0.3 is a non-breaking change, it's automatically used. More info on Version constraints can be found [here](https://dart.dev/tools/pub/dependencies#version-constraints).

**Comment by penhorwood** [comment]
I read the docs and maybe I still don't understand but I am getting this issue.

My pubspec.yaml
  geolocator: ^8.1.1
  geolocator_android: ^3.0.4

**The issue**

[map] flutter pub get
Running "flutter pub get" in map...                             
Because geolocator_android >=3.0.3 depends on geolocator_platform_interface ^3.0.0+1 and geolocator 8.1.1 depends on geolocator_platform_interface ^4.0.0, geolocator_android >=3.0.3 is incompatible with geolocator 8.1.1.
And because no versions of geolocator match >8.1.1 <9.0.0, geolocator_android >=3.0.3 is incompatible with geolocator ^8.1.1.
So, because mapapp depends on both geolocator ^8.1.1 and geolocator_android ^3.0.4, version solving failed.
pub get failed (1; So, because mapapp depends on both geolocator ^8.1.1 and geolocator_android ^3.0.4, version solving failed.)
exit code 1

**So how do I upgrade to geolocator_android 3.0.4?**
