### ISSUE TITLE
didChangeAppLifecycleState is called every time an error is thrown by determinePosition()

### ISSUE THREAD

**Issue by Poltr1** [Baseflow/flutter-geolocator#996]
Hi everyone!
I don't know if this it's intended to happen, but everytime an error is thrown by determinePosition() (except the TimeoutException thrown by getCurrentPosition()), my didChangeAppLifecycleState method it's called with state == AppLifecycleState.resumed, which triggers some updates meant to be triggered only (well... mainly) when the app is resumed.
Why does this happen? Why didChangeAppLifecycleState isn't called by the TimeoutException?

thanks!

**Comment by mvanbeusekom** [comment]
Hi @Poltr1,

The `didChangeAppLifecycleState()` is called when the App moves from the background into the foreground or when the app is automatically restarted after a crash. 

Since you mentioned the `determinePosition()` method throws an error, it is likely that your App unexpectedly crashes and the Android sub-system automatically is restarting it.

Other reasons the `didChangeAppLifecycleState()` method (with the `state == AppLifecycleState.resumed`) might be called is when the App requests permissions. Android will move your app into the background to show the permission dialog. When the permission dialog is handled by the user, Android will move your app back into the foreground and the `didChangeAppLifecycleState()` method is called.

Hope this will give you some more insight into debugging the issue. If you feel the exception thrown by the `determinePosition` method is related to a bug in the geolocator plugin please provide some more details (i.e. version of the geolocator you use, stack trace of the exception, possibly an example demonstrating the bug).

For now I will close this issue.
